import { defaultLocale, type SupportedLocale } from "./i18n";

type ClientQuestionnaireCopy = {
  metaTitle: string;
  metaDescription: string;
  selectOption: string;
  yes: string;
  no: string;
  sometimes: string;
  backToAstrologyToday: string;
  questionLabel: (n: number) => string;
  finalStep: string;
  birthTitle: string;
  monthLabel: string;
  dayLabel: string;
  yearLabel: string;
  countryOfOrigin: string;
  fieldTitle: string;
  fieldAria: string;
  sexualPreferenceTitle: string;
  drugUseTitle: string;
  helpTitle: string;
  spiritualityTitle: string;
  socioeconomicTitle: string;
  livingSituationTitle: string;
  liveAloneTitle: string;
  fastingTitle: string;
  workoutTitle: string;
  vitaminsTitle: string;
  medicationsTitle: string;
  medicationsPlaceholder: string;
  sessionTitle: string;
  frequency: string;
  duration: string;
  estimatedMembershipPrice: string;
  back: string;
  next: string;
  redirecting: string;
  proceedToCheckout: string;
  sessionFrequencyLabels: Record<"Monthly" | "Biweekly" | "Weekly", string>;
  sessionDurationLabels: Record<"30-minute" | "60-minute", string>;
  liveAloneLabels: Record<"Yes" | "No" | "Sometimes", string>;
  workFieldLabels: Record<string, string>;
  sexualPreferenceLabels: Record<string, string>;
  drugLabels: Record<string, string>;
  helpLabels: Record<string, string>;
  spiritualAffiliationLabels: Record<string, string>;
  socioeconomicLabels: Record<string, string>;
  livingSituationLabels: Record<string, string>;
  fastingLabels: Record<string, string>;
  workoutLabels: Record<string, string>;
};

const en: ClientQuestionnaireCopy = {
  metaTitle: "Client Questionnaire | Astrology Today",
  metaDescription: "Client subscription intake questionnaire for Astrology Today memberships.",
  selectOption: "Select an option",
  yes: "Yes",
  no: "No",
  sometimes: "Sometimes",
  backToAstrologyToday: "Back to Astrology Today",
  questionLabel: (n) => `Question ${n}`,
  finalStep: "Final Step",
  birthTitle: "Date of birth",
  monthLabel: "Month (MM)",
  dayLabel: "Day (DD)",
  yearLabel: "Year (YYYY)",
  countryOfOrigin: "Country of Origin",
  fieldTitle: "What is your field of work / field of interest?",
  fieldAria: "Field of work or interest",
  sexualPreferenceTitle: "Sexual Preference",
  drugUseTitle: "Drug use?",
  helpTitle: "What are you seeking help with today?",
  spiritualityTitle: "What is your spiritual affiliation?",
  socioeconomicTitle: "What is your annual salary?",
  livingSituationTitle: "What is your living situation?",
  liveAloneTitle: "Do you live alone?",
  fastingTitle: "Have you ever fasted?",
  workoutTitle: "How often do you work out?",
  vitaminsTitle: "Do you take vitamins or amino acids?",
  medicationsTitle: "Do you take any medications? Please specify.",
  medicationsPlaceholder: "Type your response here",
  sessionTitle: "Choose Session Frequency and Duration",
  frequency: "Frequency",
  duration: "Duration",
  estimatedMembershipPrice: "Estimated Membership Price",
  back: "Back",
  next: "Next",
  redirecting: "Redirecting...",
  proceedToCheckout: "Proceed to checkout",
  sessionFrequencyLabels: {
    Monthly: "Monthly",
    Biweekly: "Biweekly",
    Weekly: "Weekly",
  },
  sessionDurationLabels: {
    "30-minute": "30-minute",
    "60-minute": "60-minute",
  },
  liveAloneLabels: {
    Yes: "Yes",
    No: "No",
    Sometimes: "Sometimes",
  },
  workFieldLabels: {
    Accounting: "Accounting",
    Agriculture: "Agriculture",
    Animals: "Animals",
    Architecture: "Architecture",
    Astrology: "Astrology",
    Astronomy: "Astronomy",
    Automobiles: "Automobiles",
    Business: "Business",
    Casino: "Casino",
    Chemistry: "Chemistry",
    "Child Care": "Child Care",
    Cleaning: "Cleaning",
    Design: "Design",
    Education: "Education",
    Electricity: "Electricity",
    "Emergency Services": "Emergency Services",
    Entertainment: "Entertainment",
    Ethics: "Ethics",
    "Event Planning": "Event Planning",
    "Fashion & Beauty": "Fashion & Beauty",
    Finance: "Finance",
    Fitness: "Fitness",
    Food: "Food",
    Forestry: "Forestry",
    Fundraising: "Fundraising",
    Government: "Government",
    Jewellery: "Jewellery",
    Landscaping: "Landscaping",
    Law: "Law",
    Library: "Library",
    Logistics: "Logistics",
    Locomotives: "Locomotives",
    Medicine: "Medicine",
    Metallurgy: "Metallurgy",
    Mixology: "Mixology",
    "Mortuary Services": "Mortuary Services",
    Museum: "Museum",
    Painting: "Painting",
    "Pest Control": "Pest Control",
    Plumbing: "Plumbing",
    "Postal Service": "Postal Service",
    Psychology: "Psychology",
    "Real Estate": "Real Estate",
    "Social Work": "Social Work",
    Software: "Software",
    Spirituality: "Spirituality",
    Sports: "Sports",
    Statistics: "Statistics",
    Technology: "Technology",
    "Theme Parks": "Theme Parks",
    Other: "Other",
    Undecided: "Undecided",
  },
  sexualPreferenceLabels: {
    Heterosexual: "Heterosexual",
    Homosexual: "Homosexual",
    Bisexual: "Bisexual",
    Pansexual: "Pansexual",
    Asexual: "Asexual",
    Questioning: "Questioning",
    "Prefer not to say": "Prefer not to say",
    Other: "Other",
  },
  drugLabels: {
    Alcohol: "Alcohol",
    Cannabis: "Cannabis",
    Nicotine: "Nicotine",
    Coffee: "Coffee",
    Psychedelics: "Psychedelics",
    Stimulants: "Stimulants",
    Opioids: "Opioids",
    Benzodiazepines: "Benzodiazepines",
    "MDMA (e.g., ecstasy)": "MDMA (e.g., ecstasy)",
    Cocaine: "Cocaine",
    Heroin: "Heroin",
    Methamphetamine: "Methamphetamine",
    Ketamine: "Ketamine",
    Fentanyl: "Fentanyl",
    Other: "Other",
    "No drug use": "No drug use",
  },
  helpLabels: {
    Depression: "Depression",
    Anxiety: "Anxiety",
    Addiction: "Addiction",
    "Eating disorder": "Eating disorder",
    "Sleep disorder": "Sleep disorder",
    "Fitness training": "Fitness training",
    "Career counseling": "Career counseling",
    "Spiritual counseling": "Spiritual counseling",
    "Relationship counseling": "Relationship counseling",
    "Something else": "Something else",
  },
  spiritualAffiliationLabels: {
    Atheist: "Atheist",
    Agnostic: "Agnostic",
    "Spiritual but not religious": "Spiritual but not religious",
    Christianity: "Christianity",
    Catholicism: "Catholicism",
    "Orthodox Christianity": "Orthodox Christianity",
    "Protestant Christianity": "Protestant Christianity",
    Judaism: "Judaism",
    Islam: "Islam",
    Sufism: "Sufism",
    Hinduism: "Hinduism",
    Sikhism: "Sikhism",
    Buddhism: "Buddhism",
    Taoism: "Taoism",
    Confucianism: "Confucianism",
    Jainism: "Jainism",
    Zoroastrianism: "Zoroastrianism",
    "Baháʼí": "Baháʼí",
    Paganism: "Paganism",
    Wicca: "Wicca",
    Shamanism: "Shamanism",
    Animism: "Animism",
    "Indigenous spirituality": "Indigenous spirituality",
    Occultism: "Occultism",
    Hermeticism: "Hermeticism",
    "New Age": "New Age",
    Astrology: "Astrology",
    "Esoteric Christianity": "Esoteric Christianity",
    Gnosticism: "Gnosticism",
    Mysticism: "Mysticism",
    "Not sure": "Not sure",
    "Prefer not to say": "Prefer not to say",
  },
  socioeconomicLabels: {
    "No income": "No income",
    "$0–$20,000": "$0–$20,000",
    "$20,000–$40,000": "$20,000–$40,000",
    "$40,000–$70,000": "$40,000–$70,000",
    "$70,000–$100,000": "$70,000–$100,000",
    "$100,000–$200,000": "$100,000–$200,000",
    "$200,000+": "$200,000+",
  },
  livingSituationLabels: {
    "Rent/own": "Rent/own",
    "Live with parents": "Live with parents",
    Homeless: "Homeless",
    Nomadic: "Nomadic",
    Couchsurfing: "Couchsurfing",
    Other: "Other",
  },
  fastingLabels: {
    "Yes, intermittent fasting": "Yes, intermittent fasting",
    "Yes, long fasting": "Yes, long fasting",
    "Yes, dry fasting": "Yes, dry fasting",
    "No, never fasted": "No, never fasted",
  },
  workoutLabels: {
    "Once a month": "Once a month",
    "Once a week": "Once a week",
    "More than once a week": "More than once a week",
    Never: "Never",
  },
};

const copyByLocale: Record<SupportedLocale, ClientQuestionnaireCopy> = {
  en,
  fr: {
    ...en,
    metaTitle: "Questionnaire client | Astrology Today",
    metaDescription: "Questionnaire d'inscription client pour les abonnements Astrology Today.",
    selectOption: "Sélectionnez une option",
    yes: "Oui",
    no: "Non",
    sometimes: "Parfois",
    backToAstrologyToday: "Retour à Astrology Today",
    questionLabel: (n) => `Question ${n}`,
    finalStep: "Étape finale",
    birthTitle: "Date de naissance",
    monthLabel: "Mois (MM)",
    dayLabel: "Jour (JJ)",
    yearLabel: "Année (AAAA)",
    countryOfOrigin: "Pays d'origine",
    fieldTitle: "Quel est votre domaine de travail / d'intérêt ?",
    fieldAria: "Domaine de travail ou d'intérêt",
    sexualPreferenceTitle: "Préférence sexuelle",
    drugUseTitle: "Consommation de drogues ?",
    helpTitle: "Pour quoi cherchez-vous de l'aide aujourd'hui ?",
    spiritualityTitle: "Quelle est votre affiliation spirituelle ?",
    socioeconomicTitle: "Quel est votre revenu annuel ?",
    livingSituationTitle: "Quelle est votre situation de logement ?",
    liveAloneTitle: "Vivez-vous seul(e) ?",
    fastingTitle: "Avez-vous déjà jeûné ?",
    workoutTitle: "À quelle fréquence faites-vous de l'exercice ?",
    vitaminsTitle: "Prenez-vous des vitamines ou des acides aminés ?",
    medicationsTitle: "Prenez-vous des médicaments ? Veuillez préciser.",
    medicationsPlaceholder: "Tapez votre réponse ici",
    sessionTitle: "Choisissez la fréquence et la durée des séances",
    frequency: "Fréquence",
    duration: "Durée",
    estimatedMembershipPrice: "Prix estimé de l'abonnement",
    back: "Retour",
    next: "Suivant",
    redirecting: "Redirection...",
    proceedToCheckout: "Passer au paiement",
    sessionFrequencyLabels: { Monthly: "Mensuel", Biweekly: "Bimensuel", Weekly: "Hebdomadaire" },
    sessionDurationLabels: { "30-minute": "30 minutes", "60-minute": "60 minutes" },
    liveAloneLabels: { Yes: "Oui", No: "Non", Sometimes: "Parfois" },
    workFieldLabels: {
      Accounting: "Comptabilité", Agriculture: "Agriculture", Animals: "Animaux", Architecture: "Architecture",
      Astrology: "Astrologie", Astronomy: "Astronomie", Automobiles: "Automobile", Business: "Affaires",
      Casino: "Casino", Chemistry: "Chimie", "Child Care": "Garde d'enfants", Cleaning: "Nettoyage",
      Design: "Design", Education: "Éducation", Electricity: "Électricité", "Emergency Services": "Services d'urgence",
      Entertainment: "Divertissement", Ethics: "Éthique", "Event Planning": "Organisation d'événements", "Fashion & Beauty": "Mode et beauté",
      Finance: "Finance", Fitness: "Condition physique", Food: "Alimentation", Forestry: "Foresterie",
      Fundraising: "Collecte de fonds", Government: "Gouvernement", Jewellery: "Bijouterie", Landscaping: "Aménagement paysager",
      Law: "Droit", Library: "Bibliothèque", Logistics: "Logistique", Locomotives: "Locomotives",
      Medicine: "Médecine", Metallurgy: "Métallurgie", Mixology: "Mixologie", "Mortuary Services": "Services funéraires",
      Museum: "Musée", Painting: "Peinture", "Pest Control": "Lutte antiparasitaire", Plumbing: "Plomberie",
      "Postal Service": "Service postal", Psychology: "Psychologie", "Real Estate": "Immobilier", "Social Work": "Travail social",
      Software: "Logiciel", Spirituality: "Spiritualité", Sports: "Sports", Statistics: "Statistiques",
      Technology: "Technologie", "Theme Parks": "Parcs à thème", Other: "Autre", Undecided: "Indécis",
    },
    sexualPreferenceLabels: {
      Heterosexual: "Hétérosexuel", Homosexual: "Homosexuel", Bisexual: "Bisexuel", Pansexual: "Pansexuel",
      Asexual: "Asexuel", Questioning: "En questionnement", "Prefer not to say": "Préfère ne pas répondre", Other: "Autre",
    },
    drugLabels: {
      Alcohol: "Alcool", Cannabis: "Cannabis", Nicotine: "Nicotine", Coffee: "Café", Psychedelics: "Psychédéliques",
      Stimulants: "Stimulants", Opioids: "Opioïdes", Benzodiazepines: "Benzodiazépines", "MDMA (e.g., ecstasy)": "MDMA (p. ex., ecstasy)",
      Cocaine: "Cocaïne", Heroin: "Héroïne", Methamphetamine: "Méthamphétamine", Ketamine: "Kétamine", Fentanyl: "Fentanyl",
      Other: "Autre", "No drug use": "Aucune consommation de drogues",
    },
    helpLabels: {
      Depression: "Dépression", Anxiety: "Anxiété", Addiction: "Dépendance", "Eating disorder": "Trouble alimentaire",
      "Sleep disorder": "Trouble du sommeil", "Fitness training": "Entraînement physique", "Career counseling": "Orientation professionnelle",
      "Spiritual counseling": "Accompagnement spirituel", "Relationship counseling": "Conseil relationnel", "Something else": "Autre chose",
    },
    spiritualAffiliationLabels: {
      Atheist: "Athée", Agnostic: "Agnostique", "Spiritual but not religious": "Spirituel mais non religieux", Christianity: "Christianisme",
      Catholicism: "Catholicisme", "Orthodox Christianity": "Christianisme orthodoxe", "Protestant Christianity": "Christianisme protestant",
      Judaism: "Judaïsme", Islam: "Islam", Sufism: "Soufisme", Hinduism: "Hindouisme", Sikhism: "Sikhisme",
      Buddhism: "Bouddhisme", Taoism: "Taoïsme", Confucianism: "Confucianisme", Jainism: "Jaïnisme", Zoroastrianism: "Zoroastrisme",
      "Baháʼí": "Baháʼí", Paganism: "Paganisme", Wicca: "Wicca", Shamanism: "Chamanisme", Animism: "Animisme",
      "Indigenous spirituality": "Spiritualité autochtone", Occultism: "Occultisme", Hermeticism: "Hermétisme", "New Age": "New Age",
      Astrology: "Astrologie", "Esoteric Christianity": "Christianisme ésotérique", Gnosticism: "Gnosticisme", Mysticism: "Mysticisme",
      "Not sure": "Pas sûr", "Prefer not to say": "Préfère ne pas répondre",
    },
    socioeconomicLabels: {
      "No income": "Aucun revenu", "$0–$20,000": "0 $–20 000 $", "$20,000–$40,000": "20 000 $–40 000 $",
      "$40,000–$70,000": "40 000 $–70 000 $", "$70,000–$100,000": "70 000 $–100 000 $",
      "$100,000–$200,000": "100 000 $–200 000 $", "$200,000+": "200 000 $+",
    },
    livingSituationLabels: {
      "Rent/own": "Loue / possède", "Live with parents": "Vit avec ses parents", Homeless: "Sans-abri",
      Nomadic: "Nomade", Couchsurfing: "Hébergement chez des amis", Other: "Autre",
    },
    fastingLabels: {
      "Yes, intermittent fasting": "Oui, jeûne intermittent", "Yes, long fasting": "Oui, jeûne prolongé",
      "Yes, dry fasting": "Oui, jeûne sec", "No, never fasted": "Non, jamais jeûné",
    },
    workoutLabels: {
      "Once a month": "Une fois par mois", "Once a week": "Une fois par semaine", "More than once a week": "Plus d'une fois par semaine", Never: "Jamais",
    },
  },
  it: {
    ...en,
    metaTitle: "Questionario cliente | Astrology Today",
    metaDescription: "Questionario di iscrizione cliente per gli abbonamenti Astrology Today.",
    selectOption: "Seleziona un'opzione",
    yes: "Sì",
    no: "No",
    sometimes: "A volte",
    backToAstrologyToday: "Torna ad Astrology Today",
    questionLabel: (n) => `Domanda ${n}`,
    finalStep: "Fase finale",
    birthTitle: "Data di nascita",
    monthLabel: "Mese (MM)",
    dayLabel: "Giorno (GG)",
    yearLabel: "Anno (AAAA)",
    countryOfOrigin: "Paese di origine",
    fieldTitle: "Qual è il tuo campo di lavoro / di interesse?",
    fieldAria: "Campo di lavoro o di interesse",
    sexualPreferenceTitle: "Preferenza sessuale",
    drugUseTitle: "Uso di droghe?",
    helpTitle: "Per cosa stai cercando aiuto oggi?",
    spiritualityTitle: "Qual è la tua affiliazione spirituale?",
    socioeconomicTitle: "Qual è il tuo reddito annuale?",
    livingSituationTitle: "Qual è la tua situazione abitativa?",
    liveAloneTitle: "Vivi da solo?",
    fastingTitle: "Hai mai digiunato?",
    workoutTitle: "Quanto spesso ti alleni?",
    vitaminsTitle: "Assumi vitamine o aminoacidi?",
    medicationsTitle: "Assumi farmaci? Specifica, per favore.",
    medicationsPlaceholder: "Scrivi qui la tua risposta",
    sessionTitle: "Scegli frequenza e durata delle sessioni",
    frequency: "Frequenza",
    duration: "Durata",
    estimatedMembershipPrice: "Prezzo stimato dell'abbonamento",
    back: "Indietro",
    next: "Avanti",
    redirecting: "Reindirizzamento...",
    proceedToCheckout: "Procedi al pagamento",
    sessionFrequencyLabels: { Monthly: "Mensile", Biweekly: "Bisettimanale", Weekly: "Settimanale" },
    sessionDurationLabels: { "30-minute": "30 minuti", "60-minute": "60 minuti" },
    liveAloneLabels: { Yes: "Sì", No: "No", Sometimes: "A volte" },
    workFieldLabels: {
      Accounting: "Contabilità", Agriculture: "Agricoltura", Animals: "Animali", Architecture: "Architettura",
      Astrology: "Astrologia", Astronomy: "Astronomia", Automobiles: "Automobili", Business: "Affari",
      Casino: "Casinò", Chemistry: "Chimica", "Child Care": "Assistenza all'infanzia", Cleaning: "Pulizie",
      Design: "Design", Education: "Educazione", Electricity: "Elettricità", "Emergency Services": "Servizi di emergenza",
      Entertainment: "Intrattenimento", Ethics: "Etica", "Event Planning": "Organizzazione eventi", "Fashion & Beauty": "Moda e bellezza",
      Finance: "Finanza", Fitness: "Fitness", Food: "Alimentazione", Forestry: "Silvicoltura",
      Fundraising: "Raccolta fondi", Government: "Governo", Jewellery: "Gioielleria", Landscaping: "Paesaggistica",
      Law: "Giurisprudenza", Library: "Biblioteca", Logistics: "Logistica", Locomotives: "Locomotive",
      Medicine: "Medicina", Metallurgy: "Metallurgia", Mixology: "Mixology", "Mortuary Services": "Servizi funebri",
      Museum: "Museo", Painting: "Pittura", "Pest Control": "Disinfestazione", Plumbing: "Idraulica",
      "Postal Service": "Servizio postale", Psychology: "Psicologia", "Real Estate": "Immobiliare", "Social Work": "Lavoro sociale",
      Software: "Software", Spirituality: "Spiritualità", Sports: "Sport", Statistics: "Statistica",
      Technology: "Tecnologia", "Theme Parks": "Parchi a tema", Other: "Altro", Undecided: "Indeciso",
    },
    sexualPreferenceLabels: {
      Heterosexual: "Eterosessuale", Homosexual: "Omosessuale", Bisexual: "Bisessuale", Pansexual: "Pansessuale",
      Asexual: "Asessuale", Questioning: "In esplorazione", "Prefer not to say": "Preferisco non dirlo", Other: "Altro",
    },
    drugLabels: {
      Alcohol: "Alcol", Cannabis: "Cannabis", Nicotine: "Nicotina", Coffee: "Caffè", Psychedelics: "Psichedelici",
      Stimulants: "Stimolanti", Opioids: "Oppioidi", Benzodiazepines: "Benzodiazepine", "MDMA (e.g., ecstasy)": "MDMA (es. ecstasy)",
      Cocaine: "Cocaina", Heroin: "Eroina", Methamphetamine: "Metanfetamina", Ketamine: "Ketamina", Fentanyl: "Fentanil",
      Other: "Altro", "No drug use": "Nessun uso di droghe",
    },
    helpLabels: {
      Depression: "Depressione", Anxiety: "Ansia", Addiction: "Dipendenza", "Eating disorder": "Disturbo alimentare",
      "Sleep disorder": "Disturbo del sonno", "Fitness training": "Allenamento fitness", "Career counseling": "Consulenza di carriera",
      "Spiritual counseling": "Consulenza spirituale", "Relationship counseling": "Consulenza relazionale", "Something else": "Qualcos'altro",
    },
    spiritualAffiliationLabels: {
      Atheist: "Ateo", Agnostic: "Agnostico", "Spiritual but not religious": "Spirituale ma non religioso", Christianity: "Cristianesimo",
      Catholicism: "Cattolicesimo", "Orthodox Christianity": "Cristianesimo ortodosso", "Protestant Christianity": "Cristianesimo protestante",
      Judaism: "Ebraismo", Islam: "Islam", Sufism: "Sufismo", Hinduism: "Induismo", Sikhism: "Sikhismo",
      Buddhism: "Buddismo", Taoism: "Taoismo", Confucianism: "Confucianesimo", Jainism: "Giainismo", Zoroastrianism: "Zoroastrismo",
      "Baháʼí": "Baháʼí", Paganism: "Paganesimo", Wicca: "Wicca", Shamanism: "Sciamanesimo", Animism: "Animismo",
      "Indigenous spirituality": "Spiritualità indigena", Occultism: "Occultismo", Hermeticism: "Ermetismo", "New Age": "New Age",
      Astrology: "Astrologia", "Esoteric Christianity": "Cristianesimo esoterico", Gnosticism: "Gnosticismo", Mysticism: "Misticismo",
      "Not sure": "Non sicuro", "Prefer not to say": "Preferisco non dirlo",
    },
    socioeconomicLabels: {
      "No income": "Nessun reddito", "$0–$20,000": "$0–$20.000", "$20,000–$40,000": "$20.000–$40.000",
      "$40,000–$70,000": "$40.000–$70.000", "$70,000–$100,000": "$70.000–$100.000",
      "$100,000–$200,000": "$100.000–$200.000", "$200,000+": "$200.000+",
    },
    livingSituationLabels: {
      "Rent/own": "Affitto / proprietà", "Live with parents": "Vivo con i genitori", Homeless: "Senzatetto",
      Nomadic: "Nomade", Couchsurfing: "Ospite da amici", Other: "Altro",
    },
    fastingLabels: {
      "Yes, intermittent fasting": "Sì, digiuno intermittente", "Yes, long fasting": "Sì, digiuno prolungato",
      "Yes, dry fasting": "Sì, digiuno secco", "No, never fasted": "No, mai digiunato",
    },
    workoutLabels: {
      "Once a month": "Una volta al mese", "Once a week": "Una volta a settimana", "More than once a week": "Più di una volta a settimana", Never: "Mai",
    },
  },
  es: {
    ...en,
    metaTitle: "Cuestionario del cliente | Astrology Today",
    metaDescription: "Cuestionario de ingreso del cliente para las membresías de Astrology Today.",
    selectOption: "Seleccione una opción",
    yes: "Sí",
    no: "No",
    sometimes: "A veces",
    backToAstrologyToday: "Volver a Astrology Today",
    questionLabel: (n) => `Pregunta ${n}`,
    finalStep: "Paso final",
    birthTitle: "Fecha de nacimiento",
    monthLabel: "Mes (MM)",
    dayLabel: "Día (DD)",
    yearLabel: "Año (AAAA)",
    countryOfOrigin: "País de origen",
    fieldTitle: "¿Cuál es tu campo de trabajo / campo de interés?",
    fieldAria: "Campo de trabajo o de interés",
    sexualPreferenceTitle: "Preferencia sexual",
    drugUseTitle: "¿Consumo de drogas?",
    helpTitle: "¿En qué buscas ayuda hoy?",
    spiritualityTitle: "¿Cuál es tu afiliación espiritual?",
    socioeconomicTitle: "¿Cuál es tu salario anual?",
    livingSituationTitle: "¿Cuál es tu situación de vivienda?",
    liveAloneTitle: "¿Vives solo/a?",
    fastingTitle: "¿Has ayunado alguna vez?",
    workoutTitle: "¿Con qué frecuencia haces ejercicio?",
    vitaminsTitle: "¿Tomas vitaminas o aminoácidos?",
    medicationsTitle: "¿Tomas algún medicamento? Por favor especifica.",
    medicationsPlaceholder: "Escribe tu respuesta aquí",
    sessionTitle: "Elige frecuencia y duración de la sesión",
    frequency: "Frecuencia",
    duration: "Duración",
    estimatedMembershipPrice: "Precio estimado de la membresía",
    back: "Atrás",
    next: "Siguiente",
    redirecting: "Redirigiendo...",
    proceedToCheckout: "Proceder al pago",
    sessionFrequencyLabels: { Monthly: "Mensual", Biweekly: "Quincenal", Weekly: "Semanal" },
    sessionDurationLabels: { "30-minute": "30 minutos", "60-minute": "60 minutos" },
    liveAloneLabels: { Yes: "Sí", No: "No", Sometimes: "A veces" },
    workFieldLabels: {
      Accounting: "Contabilidad", Agriculture: "Agricultura", Animals: "Animales", Architecture: "Arquitectura",
      Astrology: "Astrología", Astronomy: "Astronomía", Automobiles: "Automóviles", Business: "Negocios",
      Casino: "Casino", Chemistry: "Química", "Child Care": "Cuidado infantil", Cleaning: "Limpieza",
      Design: "Diseño", Education: "Educación", Electricity: "Electricidad", "Emergency Services": "Servicios de emergencia",
      Entertainment: "Entretenimiento", Ethics: "Ética", "Event Planning": "Planificación de eventos", "Fashion & Beauty": "Moda y belleza",
      Finance: "Finanzas", Fitness: "Acondicionamiento físico", Food: "Alimentación", Forestry: "Silvicultura",
      Fundraising: "Recaudación de fondos", Government: "Gobierno", Jewellery: "Joyería", Landscaping: "Paisajismo",
      Law: "Derecho", Library: "Biblioteca", Logistics: "Logística", Locomotives: "Locomotoras",
      Medicine: "Medicina", Metallurgy: "Metalurgia", Mixology: "Mixología", "Mortuary Services": "Servicios funerarios",
      Museum: "Museo", Painting: "Pintura", "Pest Control": "Control de plagas", Plumbing: "Fontanería",
      "Postal Service": "Servicio postal", Psychology: "Psicología", "Real Estate": "Bienes raíces", "Social Work": "Trabajo social",
      Software: "Software", Spirituality: "Espiritualidad", Sports: "Deportes", Statistics: "Estadística",
      Technology: "Tecnología", "Theme Parks": "Parques temáticos", Other: "Otro", Undecided: "Indeciso",
    },
    sexualPreferenceLabels: {
      Heterosexual: "Heterosexual", Homosexual: "Homosexual", Bisexual: "Bisexual", Pansexual: "Pansexual",
      Asexual: "Asexual", Questioning: "Explorando", "Prefer not to say": "Prefiero no decirlo", Other: "Otro",
    },
    drugLabels: {
      Alcohol: "Alcohol", Cannabis: "Cannabis", Nicotine: "Nicotina", Coffee: "Café", Psychedelics: "Psicodélicos",
      Stimulants: "Estimulantes", Opioids: "Opioides", Benzodiazepines: "Benzodiacepinas", "MDMA (e.g., ecstasy)": "MDMA (p. ej., éxtasis)",
      Cocaine: "Cocaína", Heroin: "Heroína", Methamphetamine: "Metanfetamina", Ketamine: "Ketamina", Fentanyl: "Fentanilo",
      Other: "Otro", "No drug use": "No consumo de drogas",
    },
    helpLabels: {
      Depression: "Depresión", Anxiety: "Ansiedad", Addiction: "Adicción", "Eating disorder": "Trastorno alimentario",
      "Sleep disorder": "Trastorno del sueño", "Fitness training": "Entrenamiento físico", "Career counseling": "Orientación profesional",
      "Spiritual counseling": "Acompañamiento espiritual", "Relationship counseling": "Consejería relacional", "Something else": "Algo más",
    },
    spiritualAffiliationLabels: {
      Atheist: "Ateo", Agnostic: "Agnóstico", "Spiritual but not religious": "Espiritual pero no religioso", Christianity: "Cristianismo",
      Catholicism: "Catolicismo", "Orthodox Christianity": "Cristianismo ortodoxo", "Protestant Christianity": "Cristianismo protestante",
      Judaism: "Judaísmo", Islam: "Islam", Sufism: "Sufismo", Hinduism: "Hinduismo", Sikhism: "Sijismo",
      Buddhism: "Budismo", Taoism: "Taoísmo", Confucianism: "Confucianismo", Jainism: "Jainismo", Zoroastrianism: "Zoroastrismo",
      "Baháʼí": "Baháʼí", Paganism: "Paganismo", Wicca: "Wicca", Shamanism: "Chamanismo", Animism: "Animismo",
      "Indigenous spirituality": "Espiritualidad indígena", Occultism: "Ocultismo", Hermeticism: "Hermetismo", "New Age": "Nueva Era",
      Astrology: "Astrología", "Esoteric Christianity": "Cristianismo esotérico", Gnosticism: "Gnosticismo", Mysticism: "Misticismo",
      "Not sure": "No estoy seguro", "Prefer not to say": "Prefiero no decirlo",
    },
    socioeconomicLabels: {
      "No income": "Sin ingresos", "$0–$20,000": "$0–$20,000", "$20,000–$40,000": "$20,000–$40,000",
      "$40,000–$70,000": "$40,000–$70,000", "$70,000–$100,000": "$70,000–$100,000",
      "$100,000–$200,000": "$100,000–$200,000", "$200,000+": "$200,000+",
    },
    livingSituationLabels: {
      "Rent/own": "Alquila / posee", "Live with parents": "Vive con sus padres", Homeless: "Sin hogar",
      Nomadic: "Nómada", Couchsurfing: "Alojamiento en sofás", Other: "Otro",
    },
    fastingLabels: {
      "Yes, intermittent fasting": "Sí, ayuno intermitente", "Yes, long fasting": "Sí, ayuno prolongado",
      "Yes, dry fasting": "Sí, ayuno seco", "No, never fasted": "No, nunca he ayunado",
    },
    workoutLabels: {
      "Once a month": "Una vez al mes", "Once a week": "Una vez a la semana", "More than once a week": "Más de una vez a la semana", Never: "Nunca",
    },
  },
  hi: {
    ...en,
    metaTitle: "क्लाइंट प्रश्नावली | Astrology Today",
    metaDescription: "Astrology Today सदस्यताओं के लिए क्लाइंट इनटेक प्रश्नावली।",
    selectOption: "एक विकल्प चुनें",
    yes: "हाँ",
    no: "नहीं",
    sometimes: "कभी-कभी",
    backToAstrologyToday: "Astrology Today पर वापस जाएँ",
    questionLabel: (n) => `प्रश्न ${n}`,
    finalStep: "अंतिम चरण",
    birthTitle: "जन्म तिथि",
    monthLabel: "माह (MM)",
    dayLabel: "दिन (DD)",
    yearLabel: "वर्ष (YYYY)",
    countryOfOrigin: "मूल देश",
    fieldTitle: "आपका कार्यक्षेत्र / रुचि का क्षेत्र क्या है?",
    fieldAria: "कार्य या रुचि का क्षेत्र",
    sexualPreferenceTitle: "यौन अभिरुचि",
    drugUseTitle: "नशा उपयोग?",
    helpTitle: "आज आप किस बात में सहायता चाह रहे हैं?",
    spiritualityTitle: "आपकी आध्यात्मिक संबद्धता क्या है?",
    socioeconomicTitle: "आपकी वार्षिक आय क्या है?",
    livingSituationTitle: "आपकी रहने की स्थिति क्या है?",
    liveAloneTitle: "क्या आप अकेले रहते हैं?",
    fastingTitle: "क्या आपने कभी उपवास किया है?",
    workoutTitle: "आप कितनी बार व्यायाम करते हैं?",
    vitaminsTitle: "क्या आप विटामिन या अमीनो एसिड लेते हैं?",
    medicationsTitle: "क्या आप कोई दवाइयाँ लेते हैं? कृपया बताइए।",
    medicationsPlaceholder: "अपना उत्तर यहाँ लिखें",
    sessionTitle: "सत्र की आवृत्ति और अवधि चुनें",
    frequency: "आवृत्ति",
    duration: "अवधि",
    estimatedMembershipPrice: "अनुमानित सदस्यता मूल्य",
    back: "वापस",
    next: "अगला",
    redirecting: "रीडायरेक्ट हो रहा है...",
    proceedToCheckout: "चेकआउट पर जाएँ",
    sessionFrequencyLabels: { Monthly: "मासिक", Biweekly: "पाक्षिक", Weekly: "साप्ताहिक" },
    sessionDurationLabels: { "30-minute": "30 मिनट", "60-minute": "60 मिनट" },
    liveAloneLabels: { Yes: "हाँ", No: "नहीं", Sometimes: "कभी-कभी" },
    workFieldLabels: {
      Accounting: "लेखा", Agriculture: "कृषि", Animals: "पशु", Architecture: "वास्तुकला", Astrology: "ज्योतिष", Astronomy: "खगोलशास्त्र",
      Automobiles: "ऑटोमोबाइल", Business: "व्यवसाय", Casino: "कैसीनो", Chemistry: "रसायन विज्ञान", "Child Care": "बाल देखभाल",
      Cleaning: "सफाई", Design: "डिज़ाइन", Education: "शिक्षा", Electricity: "बिजली", "Emergency Services": "आपातकालीन सेवाएँ",
      Entertainment: "मनोरंजन", Ethics: "नीतिशास्त्र", "Event Planning": "कार्यक्रम योजना", "Fashion & Beauty": "फैशन और सौंदर्य",
      Finance: "वित्त", Fitness: "फिटनेस", Food: "भोजन", Forestry: "वानिकी", Fundraising: "धन संग्रह", Government: "सरकार",
      Jewellery: "आभूषण", Landscaping: "भूदृश्य निर्माण", Law: "कानून", Library: "पुस्तकालय", Logistics: "लॉजिस्टिक्स",
      Locomotives: "रेल इंजन", Medicine: "चिकित्सा", Metallurgy: "धातुकर्म", Mixology: "मिक्सोलॉजी", "Mortuary Services": "अंत्येष्टि सेवाएँ",
      Museum: "संग्रहालय", Painting: "चित्रकला", "Pest Control": "कीट नियंत्रण", Plumbing: "प्लंबिंग", "Postal Service": "डाक सेवा",
      Psychology: "मनोविज्ञान", "Real Estate": "रियल एस्टेट", "Social Work": "सामाजिक कार्य", Software: "सॉफ़्टवेयर",
      Spirituality: "आध्यात्मिकता", Sports: "खेल", Statistics: "सांख्यिकी", Technology: "प्रौद्योगिकी", "Theme Parks": "थीम पार्क",
      Other: "अन्य", Undecided: "अनिर्णीत",
    },
    sexualPreferenceLabels: {
      Heterosexual: "विषमलैंगिक", Homosexual: "समलैंगिक", Bisexual: "उभयलिंगी", Pansexual: "पैनसेक्शुअल",
      Asexual: "अलैंगिक", Questioning: "अन्वेषण में", "Prefer not to say": "कहना पसंद नहीं", Other: "अन्य",
    },
    drugLabels: {
      Alcohol: "अल्कोहल", Cannabis: "कैनाबिस", Nicotine: "निकोटीन", Coffee: "कॉफी", Psychedelics: "साइकेडेलिक्स",
      Stimulants: "उत्तेजक", Opioids: "ओपिओइड", Benzodiazepines: "बेंज़ोडायज़ेपाइन्स", "MDMA (e.g., ecstasy)": "MDMA (जैसे एक्स्टेसी)",
      Cocaine: "कोकीन", Heroin: "हेरोइन", Methamphetamine: "मेथाम्फेटामीन", Ketamine: "केटामीन", Fentanyl: "फेंटानिल",
      Other: "अन्य", "No drug use": "नशीली दवाओं का उपयोग नहीं",
    },
    helpLabels: {
      Depression: "अवसाद", Anxiety: "चिंता", Addiction: "लत", "Eating disorder": "खान-पान विकार", "Sleep disorder": "नींद विकार",
      "Fitness training": "फिटनेस प्रशिक्षण", "Career counseling": "कैरियर परामर्श", "Spiritual counseling": "आध्यात्मिक परामर्श",
      "Relationship counseling": "रिश्ता परामर्श", "Something else": "कुछ और",
    },
    spiritualAffiliationLabels: {
      Atheist: "नास्तिक", Agnostic: "अज्ञेयवादी", "Spiritual but not religious": "आध्यात्मिक पर धार्मिक नहीं", Christianity: "ईसाई धर्म",
      Catholicism: "कैथोलिक धर्म", "Orthodox Christianity": "ऑर्थोडॉक्स ईसाई धर्म", "Protestant Christianity": "प्रोटेस्टेंट ईसाई धर्म",
      Judaism: "यहूदी धर्म", Islam: "इस्लाम", Sufism: "सूफ़ीवाद", Hinduism: "हिंदू धर्म", Sikhism: "सिख धर्म", Buddhism: "बौद्ध धर्म",
      Taoism: "ताओवाद", Confucianism: "कन्फ्यूशियसवाद", Jainism: "जैन धर्म", Zoroastrianism: "जरथुस्त्र धर्म", "Baháʼí": "बहाई",
      Paganism: "पैगनवाद", Wicca: "विक्का", Shamanism: "शमनवाद", Animism: "आनिमिज़्म", "Indigenous spirituality": "स्वदेशी आध्यात्मिकता",
      Occultism: "गूढ़वाद", Hermeticism: "हर्मेटिसिज़्म", "New Age": "न्यू एज", Astrology: "ज्योतिष",
      "Esoteric Christianity": "गूढ़ ईसाई धर्म", Gnosticism: "ज्ञानवाद", Mysticism: "रहस्यवाद", "Not sure": "निश्चित नहीं", "Prefer not to say": "कहना पसंद नहीं",
    },
    socioeconomicLabels: {
      "No income": "कोई आय नहीं", "$0–$20,000": "$0–$20,000", "$20,000–$40,000": "$20,000–$40,000",
      "$40,000–$70,000": "$40,000–$70,000", "$70,000–$100,000": "$70,000–$100,000", "$100,000–$200,000": "$100,000–$200,000", "$200,000+": "$200,000+",
    },
    livingSituationLabels: {
      "Rent/own": "किराये पर / स्वामित्व", "Live with parents": "माता-पिता के साथ रहते हैं", Homeless: "बेघर", Nomadic: "घुमंतू", Couchsurfing: "काउचसर्फिंग", Other: "अन्य",
    },
    fastingLabels: {
      "Yes, intermittent fasting": "हाँ, अंतराल उपवास", "Yes, long fasting": "हाँ, लंबा उपवास", "Yes, dry fasting": "हाँ, शुष्क उपवास", "No, never fasted": "नहीं, कभी उपवास नहीं किया",
    },
    workoutLabels: {
      "Once a month": "महीने में एक बार", "Once a week": "सप्ताह में एक बार", "More than once a week": "सप्ताह में एक से अधिक बार", Never: "कभी नहीं",
    },
  },
  ur: {
    ...en,
    metaTitle: "کلائنٹ سوالنامہ | Astrology Today",
    metaDescription: "Astrology Today رکنیتوں کے لیے کلائنٹ انٹیک سوالنامہ۔",
    selectOption: "ایک اختیار منتخب کریں",
    yes: "ہاں",
    no: "نہیں",
    sometimes: "کبھی کبھار",
    backToAstrologyToday: "Astrology Today پر واپس جائیں",
    questionLabel: (n) => `سوال ${n}`,
    finalStep: "آخری مرحلہ",
    birthTitle: "تاریخ پیدائش",
    monthLabel: "مہینہ (MM)",
    dayLabel: "دن (DD)",
    yearLabel: "سال (YYYY)",
    countryOfOrigin: "آبائی ملک",
    fieldTitle: "آپ کا شعبۂ کار / دلچسپی کا شعبہ کیا ہے؟",
    fieldAria: "شعبۂ کار یا دلچسپی",
    sexualPreferenceTitle: "جنسی ترجیح",
    drugUseTitle: "منشیات کا استعمال؟",
    helpTitle: "آپ آج کس معاملے میں مدد چاہتے ہیں؟",
    spiritualityTitle: "آپ کی روحانی وابستگی کیا ہے؟",
    socioeconomicTitle: "آپ کی سالانہ آمدنی کیا ہے؟",
    livingSituationTitle: "آپ کی رہائش کی صورتحال کیا ہے؟",
    liveAloneTitle: "کیا آپ اکیلے رہتے ہیں؟",
    fastingTitle: "کیا آپ نے کبھی روزہ رکھا ہے؟",
    workoutTitle: "آپ کتنی بار ورزش کرتے ہیں؟",
    vitaminsTitle: "کیا آپ وٹامن یا امینو ایسڈ لیتے ہیں؟",
    medicationsTitle: "کیا آپ کوئی دوائیں لیتے ہیں؟ براہ کرم وضاحت کریں۔",
    medicationsPlaceholder: "اپنا جواب یہاں لکھیں",
    sessionTitle: "سیشن کی فریکوئنسی اور دورانیہ منتخب کریں",
    frequency: "فریکوئنسی",
    duration: "دورانیہ",
    estimatedMembershipPrice: "متوقع رکنیت قیمت",
    back: "واپس",
    next: "اگلا",
    redirecting: "منتقل کیا جا رہا ہے...",
    proceedToCheckout: "چیک آؤٹ پر جائیں",
    sessionFrequencyLabels: { Monthly: "ماہانہ", Biweekly: "دو ہفتہ وار", Weekly: "ہفتہ وار" },
    sessionDurationLabels: { "30-minute": "30 منٹ", "60-minute": "60 منٹ" },
    liveAloneLabels: { Yes: "ہاں", No: "نہیں", Sometimes: "کبھی کبھار" },
    workFieldLabels: {
      Accounting: "اکاؤنٹنگ", Agriculture: "زراعت", Animals: "جانور", Architecture: "معماری", Astrology: "علمِ نجوم", Astronomy: "فلکیات",
      Automobiles: "گاڑیاں", Business: "کاروبار", Casino: "کیسینو", Chemistry: "کیمیا", "Child Care": "بچوں کی دیکھ بھال", Cleaning: "صفائی",
      Design: "ڈیزائن", Education: "تعلیم", Electricity: "بجلی", "Emergency Services": "ہنگامی خدمات", Entertainment: "تفریح", Ethics: "اخلاقیات",
      "Event Planning": "تقریبات کی منصوبہ بندی", "Fashion & Beauty": "فیشن اور خوبصورتی", Finance: "مالیات", Fitness: "فٹنس", Food: "خوراک",
      Forestry: "جنگلات", Fundraising: "فنڈ ریزنگ", Government: "حکومت", Jewellery: "زیورات", Landscaping: "لینڈ سکیپنگ", Law: "قانون",
      Library: "لائبریری", Logistics: "لاجسٹکس", Locomotives: "ریل انجن", Medicine: "طب", Metallurgy: "دھات کاری", Mixology: "مکسولوجی",
      "Mortuary Services": "تدفینی خدمات", Museum: "میوزیم", Painting: "مصوری", "Pest Control": "کیڑوں کا کنٹرول", Plumbing: "پلمبنگ",
      "Postal Service": "ڈاک سروس", Psychology: "نفسیات", "Real Estate": "رئیل اسٹیٹ", "Social Work": "سماجی کام", Software: "سافٹ ویئر",
      Spirituality: "روحانیت", Sports: "کھیل", Statistics: "شماریات", Technology: "ٹیکنالوجی", "Theme Parks": "تھیم پارکس", Other: "دیگر", Undecided: "غیر فیصلہ شدہ",
    },
    sexualPreferenceLabels: {
      Heterosexual: "ہم جنس مخالف کی طرف میلان", Homosexual: "ہم جنس کی طرف میلان", Bisexual: "دو طرفہ جنسی میلان", Pansexual: "پین سیکشوئل",
      Asexual: "غیر جنسی", Questioning: "تلاش میں", "Prefer not to say": "بتانا پسند نہیں", Other: "دیگر",
    },
    drugLabels: {
      Alcohol: "شراب", Cannabis: "کینابس", Nicotine: "نکوٹین", Coffee: "کافی", Psychedelics: "سائیکیڈیلیکس", Stimulants: "محرکات",
      Opioids: "اوپی اوئڈز", Benzodiazepines: "بینزوڈایازیپائنز", "MDMA (e.g., ecstasy)": "ایم ڈی ایم اے (مثلاً ایکسٹیسی)", Cocaine: "کوکین",
      Heroin: "ہیروئن", Methamphetamine: "میتھامفیٹامین", Ketamine: "کیٹامین", Fentanyl: "فینٹانل", Other: "دیگر", "No drug use": "منشیات کا استعمال نہیں",
    },
    helpLabels: {
      Depression: "افسردگی", Anxiety: "بے چینی", Addiction: "لت", "Eating disorder": "کھانے کی خرابی", "Sleep disorder": "نیند کی خرابی",
      "Fitness training": "فٹنس ٹریننگ", "Career counseling": "کیریئر مشاورت", "Spiritual counseling": "روحانی مشاورت", "Relationship counseling": "رشتوں کی مشاورت", "Something else": "کچھ اور",
    },
    spiritualAffiliationLabels: {
      Atheist: "ملحد", Agnostic: "لا ادری", "Spiritual but not religious": "روحانی لیکن مذہبی نہیں", Christianity: "عیسائیت", Catholicism: "کیتھولک عیسائیت",
      "Orthodox Christianity": "آرتھوڈوکس عیسائیت", "Protestant Christianity": "پروٹسٹنٹ عیسائیت", Judaism: "یہودیت", Islam: "اسلام", Sufism: "تصوف",
      Hinduism: "ہندومت", Sikhism: "سکھ مت", Buddhism: "بدھ مت", Taoism: "تاؤ مت", Confucianism: "کنفیوشس مت", Jainism: "جین مت",
      Zoroastrianism: "زرتشتیت", "Baháʼí": "بہائی", Paganism: "قدیم مشرکانہ عقائد", Wicca: "وِکّا", Shamanism: "شامانیت", Animism: "جاندار پرستی",
      "Indigenous spirituality": "مقامی روحانیت", Occultism: "خفیہ علوم", Hermeticism: "ہرمٹزم", "New Age": "نیو ایج", Astrology: "علمِ نجوم",
      "Esoteric Christianity": "باطنی عیسائیت", Gnosticism: "گنوسٹک ازم", Mysticism: "عرفان", "Not sure": "یقین نہیں", "Prefer not to say": "بتانا پسند نہیں",
    },
    socioeconomicLabels: {
      "No income": "کوئی آمدنی نہیں", "$0–$20,000": "$0–$20,000", "$20,000–$40,000": "$20,000–$40,000", "$40,000–$70,000": "$40,000–$70,000",
      "$70,000–$100,000": "$70,000–$100,000", "$100,000–$200,000": "$100,000–$200,000", "$200,000+": "$200,000+",
    },
    livingSituationLabels: {
      "Rent/own": "کرائے پر / اپنی ملکیت", "Live with parents": "والدین کے ساتھ رہتے ہیں", Homeless: "بے گھر", Nomadic: "خانہ بدوش", Couchsurfing: "عارضی قیام", Other: "دیگر",
    },
    fastingLabels: {
      "Yes, intermittent fasting": "ہاں، وقفے وقفے سے روزہ", "Yes, long fasting": "ہاں، طویل روزہ", "Yes, dry fasting": "ہاں، خشک روزہ", "No, never fasted": "نہیں، کبھی روزہ نہیں رکھا",
    },
    workoutLabels: {
      "Once a month": "مہینے میں ایک بار", "Once a week": "ہفتے میں ایک بار", "More than once a week": "ہفتے میں ایک سے زیادہ بار", Never: "کبھی نہیں",
    },
  },
  sa: {
    ...en,
    metaTitle: "ग्राहक-प्रश्नावली | Astrology Today",
    metaDescription: "Astrology Today सदस्यताभ्यः ग्राहक-प्रवेश-प्रश्नावली।",
    selectOption: "विकल्पं चिनुत",
    yes: "आम्",
    no: "न",
    sometimes: "कदाचित्",
    backToAstrologyToday: "Astrology Today प्रति प्रत्यागच्छतु",
    questionLabel: (n) => `प्रश्नः ${n}`,
    finalStep: "अन्तिम-चरणः",
    birthTitle: "जन्म-तिथिः",
    monthLabel: "मासः (MM)",
    dayLabel: "दिनम् (DD)",
    yearLabel: "वर्षम् (YYYY)",
    countryOfOrigin: "मूल-देशः",
    fieldTitle: "भवतः कार्यक्षेत्रं / रुचिक्षेत्रं किम्?",
    fieldAria: "कार्य-वा-रुचिक्षेत्रम्",
    sexualPreferenceTitle: "यौन-प्राधान्यम्",
    drugUseTitle: "औषध-द्रव्य-उपयोगः?",
    helpTitle: "अद्य भवन्तः कस्मिन् विषये साहाय्यम् इच्छन्ति?",
    spiritualityTitle: "भवतः आध्यात्मिक-संबद्धता का?",
    socioeconomicTitle: "भवतः वार्षिक-आयः का?",
    livingSituationTitle: "भवतः निवास-स्थिति: का?",
    liveAloneTitle: "किं भवान् एकाकी वसति?",
    fastingTitle: "किं भवान् कदापि उपवासम् अकरोत्?",
    workoutTitle: "भवान् कियत् वारं व्यायामं करोति?",
    vitaminsTitle: "किं भवान् विटामिनानि वा अमीनो-अम्लानि गृह्णाति?",
    medicationsTitle: "किं भवान् औषधानि गृह्णाति? कृपया निर्दिशतु।",
    medicationsPlaceholder: "अत्र स्वउत्तरं लिखतु",
    sessionTitle: "सत्र-आवृत्तिं कालावधिं च चिनुत",
    frequency: "आवृत्तिः",
    duration: "कालावधिः",
    estimatedMembershipPrice: "अनुमानित-सदस्यता-मूल्यम्",
    back: "प्रत्यागच्छ",
    next: "अनन्तरम्",
    redirecting: "पुनर्निर्देशनं भवति...",
    proceedToCheckout: "भुगतान-पटलं गच्छतु",
    sessionFrequencyLabels: { Monthly: "मासिकम्", Biweekly: "द्विसाप्ताहिकम्", Weekly: "साप्ताहिकम्" },
    sessionDurationLabels: { "30-minute": "३० निमेषाः", "60-minute": "६० निमेषाः" },
    liveAloneLabels: { Yes: "आम्", No: "न", Sometimes: "कदाचित्" },
    workFieldLabels: {
      Accounting: "लेखाशास्त्रम्", Agriculture: "कृषिः", Animals: "पशवः", Architecture: "वास्तुशिल्पम्", Astrology: "ज्योतिषम्", Astronomy: "खगोलशास्त्रम्",
      Automobiles: "यानानि", Business: "व्यवसायः", Casino: "क्रीडागृहः", Chemistry: "रसायनशास्त्रम्", "Child Care": "बाल-परिचर्या", Cleaning: "मार्जनम्",
      Design: "आलेखनम्", Education: "शिक्षा", Electricity: "विद्युत्", "Emergency Services": "आपत्कालीन-सेवाः", Entertainment: "मनोरञ्जनम्", Ethics: "नीतिशास्त्रम्",
      "Event Planning": "कार्यक्रम-योजना", "Fashion & Beauty": "वस्त्र-रूप-सौन्दर्यम्", Finance: "वित्तम्", Fitness: "शारीरिक-तत्परता", Food: "भोजनम्",
      Forestry: "वनपालनम्", Fundraising: "धनसंग्रहः", Government: "शासनम्", Jewellery: "आभरणम्", Landscaping: "उद्यान-रचना", Law: "विधिः",
      Library: "ग्रन्थालयः", Logistics: "रसद्-व्यवस्था", Locomotives: "रेल-इञ्जनानि", Medicine: "चिकित्सा", Metallurgy: "धातुशास्त्रम्", Mixology: "पेय-निर्माण-विद्या",
      "Mortuary Services": "अन्त्येष्टि-सेवाः", Museum: "संग्रहालयः", Painting: "चित्रकला", "Pest Control": "कीट-नियन्त्रणम्", Plumbing: "नलिकाकर्म",
      "Postal Service": "डाक-सेवा", Psychology: "मनोविज्ञानम्", "Real Estate": "स्थावर-सम्पत्तिः", "Social Work": "सामाजिक-कार्यं", Software: "सॉफ्टवेयरम्",
      Spirituality: "आध्यात्मिकता", Sports: "क्रीडाः", Statistics: "साङ्ख्यिकी", Technology: "प्रौद्योगिकी", "Theme Parks": "विषय-उद्यानानि", Other: "अन्यत्", Undecided: "अनिर्णीतम्",
    },
    sexualPreferenceLabels: {
      Heterosexual: "विपरीतलिङ्ग-आकर्षणम्", Homosexual: "समलिङ्ग-आकर्षणम्", Bisexual: "उभयलिङ्ग-आकर्षणम्", Pansexual: "सर्वलिङ्ग-आकर्षणम्",
      Asexual: "अलैङ्गिकम्", Questioning: "अन्वेषणे", "Prefer not to say": "वक्तुं न इच्छामि", Other: "अन्यत्",
    },
    drugLabels: {
      Alcohol: "मद्यं", Cannabis: "कैनाबिस्", Nicotine: "निकोटिन्", Coffee: "काफी", Psychedelics: "मनोविस्तारक-द्रव्याणि", Stimulants: "उत्तेजकानि",
      Opioids: "ओपिऑइड्-द्रव्याणि", Benzodiazepines: "बेन्जोडायजेपाइन्स्", "MDMA (e.g., ecstasy)": "एम्-डी-एम्-ए (यथा एक्स्टेसी)", Cocaine: "कोकेन", Heroin: "हेरोइन",
      Methamphetamine: "मेथाम्फेटामीन्", Ketamine: "केटामीन्", Fentanyl: "फेन्टानिल्", Other: "अन्यत्", "No drug use": "औषध-द्रव्य-उपयोगो नास्ति",
    },
    helpLabels: {
      Depression: "अवसादः", Anxiety: "चिन्ता", Addiction: "आसक्तिः", "Eating disorder": "भोजन-विकारः", "Sleep disorder": "निद्रा-विकारः",
      "Fitness training": "व्यायाम-प्रशिक्षणम्", "Career counseling": "व्यवसाय-परामर्शः", "Spiritual counseling": "आध्यात्मिक-परामर्शः", "Relationship counseling": "सम्बन्ध-परामर्शः", "Something else": "अन्यत् किञ्चित्",
    },
    spiritualAffiliationLabels: {
      Atheist: "नास्तिकः", Agnostic: "अज्ञेयवादी", "Spiritual but not religious": "आध्यात्मिकः किन्तु अमतसम्बद्धः", Christianity: "ईसाई-मतम्", Catholicism: "कैथोलिक-मतम्",
      "Orthodox Christianity": "ऑर्थोडॉक्स-ईसाई-मतम्", "Protestant Christianity": "प्रोटेस्टन्ट-ईसाई-मतम्", Judaism: "यहूदी-मतम्", Islam: "इस्लाम्", Sufism: "सूफी-मतम्",
      Hinduism: "हिन्दू-मतम्", Sikhism: "सिख-मतम्", Buddhism: "बौद्ध-मतम्", Taoism: "ताओ-मतम्", Confucianism: "कन्फ्यूशिय-मतम्", Jainism: "जैन-मतम्",
      Zoroastrianism: "जरथुष्ट्र-मतम्", "Baháʼí": "बहाई-मतम्", Paganism: "पैगन-मतम्", Wicca: "विक्का", Shamanism: "शामनिक-मतम्", Animism: "प्राणवादः",
      "Indigenous spirituality": "आदिवासी-आध्यात्मिकता", Occultism: "गूढवादः", Hermeticism: "हर्मेटिक-मतम्", "New Age": "न्यू-एज्", Astrology: "ज्योतिषम्",
      "Esoteric Christianity": "गूढ-ईसाई-मतम्", Gnosticism: "ज्ञानवादः", Mysticism: "रहस्यवादः", "Not sure": "न निश्चितम्", "Prefer not to say": "वक्तुं न इच्छामि",
    },
    socioeconomicLabels: {
      "No income": "आयः नास्ति", "$0–$20,000": "$0–$20,000", "$20,000–$40,000": "$20,000–$40,000", "$40,000–$70,000": "$40,000–$70,000",
      "$70,000–$100,000": "$70,000–$100,000", "$100,000–$200,000": "$100,000–$200,000", "$200,000+": "$200,000+",
    },
    livingSituationLabels: {
      "Rent/own": "भाडे / स्वामित्व", "Live with parents": "माता-पित्रोः सह वसति", Homeless: "अनिवासी", Nomadic: "यायावरः", Couchsurfing: "मित्रगृहेषु निवासः", Other: "अन्यत्",
    },
    fastingLabels: {
      "Yes, intermittent fasting": "आम्, अन्तराल-उपवासः", "Yes, long fasting": "आम्, दीर्घ-उपवासः", "Yes, dry fasting": "आम्, शुष्क-उपवासः", "No, never fasted": "न, कदापि उपवासः न कृतः",
    },
    workoutLabels: {
      "Once a month": "मासे एकवारम्", "Once a week": "सप्ताहे एकवारम्", "More than once a week": "सप्ताहे एकवारात् अधिकम्", Never: "कदापि न",
    },
  },
  pa: {
    ...en,
    metaTitle: "ਕਲਾਇੰਟ ਪ੍ਰਸ਼ਨਾਵਲੀ | Astrology Today",
    metaDescription: "Astrology Today ਮੈਂਬਰਸ਼ਿਪਾਂ ਲਈ ਕਲਾਇੰਟ ਇੰਟੇਕ ਪ੍ਰਸ਼ਨਾਵਲੀ।",
    selectOption: "ਇੱਕ ਵਿਕਲਪ ਚੁਣੋ",
    yes: "ਹਾਂ",
    no: "ਨਹੀਂ",
    sometimes: "ਕਦੇ-ਕਦੇ",
    backToAstrologyToday: "Astrology Today ਤੇ ਵਾਪਸ ਜਾਓ",
    questionLabel: (n) => `ਸਵਾਲ ${n}`,
    finalStep: "ਅੰਤਿਮ ਕਦਮ",
    birthTitle: "ਜਨਮ ਮਿਤੀ",
    monthLabel: "ਮਹੀਨਾ (MM)",
    dayLabel: "ਦਿਨ (DD)",
    yearLabel: "ਸਾਲ (YYYY)",
    countryOfOrigin: "ਮੂਲ ਦੇਸ਼",
    fieldTitle: "ਤੁਹਾਡਾ ਕੰਮ ਦਾ ਖੇਤਰ / ਦਿਲਚਸਪੀ ਦਾ ਖੇਤਰ ਕੀ ਹੈ?",
    fieldAria: "ਕੰਮ ਜਾਂ ਦਿਲਚਸਪੀ ਦਾ ਖੇਤਰ",
    sexualPreferenceTitle: "ਲੈੰਗਿਕ ਪਸੰਦ",
    drugUseTitle: "ਨਸ਼ੀਲੇ ਪਦਾਰਥਾਂ ਦੀ ਵਰਤੋਂ?",
    helpTitle: "ਅੱਜ ਤੁਸੀਂ ਕਿਸ ਗੱਲ ਵਿੱਚ ਮਦਦ ਲੱਭ ਰਹੇ ਹੋ?",
    spiritualityTitle: "ਤੁਹਾਡੀ ਆਧਿਆਤਮਿਕ ਸੰਬੰਧਤਾ ਕੀ ਹੈ?",
    socioeconomicTitle: "ਤੁਹਾਡੀ ਸਾਲਾਨਾ ਆਮਦਨ ਕੀ ਹੈ?",
    livingSituationTitle: "ਤੁਹਾਡੀ ਰਹਿਣ ਦੀ ਸਥਿਤੀ ਕੀ ਹੈ?",
    liveAloneTitle: "ਕੀ ਤੁਸੀਂ ਇਕੱਲੇ ਰਹਿੰਦੇ ਹੋ?",
    fastingTitle: "ਕੀ ਤੁਸੀਂ ਕਦੇ ਉਪਵਾਸ ਕੀਤਾ ਹੈ?",
    workoutTitle: "ਤੁਸੀਂ ਕਿੰਨੀ ਵਾਰ ਵਰਜ਼ਿਸ਼ ਕਰਦੇ ਹੋ?",
    vitaminsTitle: "ਕੀ ਤੁਸੀਂ ਵਿਟਾਮਿਨ ਜਾਂ ਐਮੀਨੋ ਐਸਿਡ ਲੈਂਦੇ ਹੋ?",
    medicationsTitle: "ਕੀ ਤੁਸੀਂ ਕੋਈ ਦਵਾਈਆਂ ਲੈਂਦੇ ਹੋ? ਕਿਰਪਾ ਕਰਕੇ ਦੱਸੋ।",
    medicationsPlaceholder: "ਆਪਣਾ ਜਵਾਬ ਇੱਥੇ ਲਿਖੋ",
    sessionTitle: "ਸੈਸ਼ਨ ਦੀ ਆਵ੍ਰਿਤੀ ਅਤੇ ਮਿਆਦ ਚੁਣੋ",
    frequency: "ਆਵ੍ਰਿਤੀ",
    duration: "ਮਿਆਦ",
    estimatedMembershipPrice: "ਅਨੁਮਾਨਿਤ ਮੈਂਬਰਸ਼ਿਪ ਕੀਮਤ",
    back: "ਵਾਪਸ",
    next: "ਅੱਗੇ",
    redirecting: "ਰੀਡਾਇਰੈਕਟ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    proceedToCheckout: "ਚੈਕਆਉਟ ਵੱਲ ਜਾਓ",
    sessionFrequencyLabels: { Monthly: "ਮਾਸਿਕ", Biweekly: "ਦੋ ਹਫ਼ਤਿਆਂ ਬਾਅਦ", Weekly: "ਹਫ਼ਤਾਵਾਰੀ" },
    sessionDurationLabels: { "30-minute": "30 ਮਿੰਟ", "60-minute": "60 ਮਿੰਟ" },
    liveAloneLabels: { Yes: "ਹਾਂ", No: "ਨਹੀਂ", Sometimes: "ਕਦੇ-ਕਦੇ" },
    workFieldLabels: {
      Accounting: "ਲੇਖਾ-ਜੋਖਾ", Agriculture: "ਖੇਤੀਬਾੜੀ", Animals: "ਜਾਨਵਰ", Architecture: "ਵਾਸਤੁਕਲਾ", Astrology: "ਜੋਤਿਸ਼", Astronomy: "ਖਗੋਲ ਵਿਗਿਆਨ",
      Automobiles: "ਗੱਡੀਆਂ", Business: "ਕਾਰੋਬਾਰ", Casino: "ਕੈਸੀਨੋ", Chemistry: "ਰਸਾਇਣ ਵਿਗਿਆਨ", "Child Care": "ਬੱਚਿਆਂ ਦੀ ਦੇਖਭਾਲ", Cleaning: "ਸਫਾਈ",
      Design: "ਡਿਜ਼ਾਈਨ", Education: "ਸ਼ਿੱਖਿਆ", Electricity: "ਬਿਜਲੀ", "Emergency Services": "ਐਮਰਜੈਂਸੀ ਸੇਵਾਵਾਂ", Entertainment: "ਮਨੋਰੰਜਨ", Ethics: "ਨੈਤਿਕਤਾ",
      "Event Planning": "ਕਾਰਜਕ੍ਰਮ ਯੋਜਨਾ", "Fashion & Beauty": "ਫੈਸ਼ਨ ਅਤੇ ਸੁੰਦਰਤਾ", Finance: "ਵਿੱਤ", Fitness: "ਫਿਟਨੈੱਸ", Food: "ਭੋਜਨ",
      Forestry: "ਵਨ ਸੰਭਾਲ", Fundraising: "ਫੰਡ ਇਕੱਠਾ ਕਰਨਾ", Government: "ਸਰਕਾਰ", Jewellery: "ਗਹਿਣੇ", Landscaping: "ਲੈਂਡਸਕੇਪਿੰਗ", Law: "ਕਾਨੂੰਨ",
      Library: "ਲਾਇਬ੍ਰੇਰੀ", Logistics: "ਲੋਜਿਸਟਿਕਸ", Locomotives: "ਰੇਲ ਇੰਜਣ", Medicine: "ਚਿਕਿਤਸਾ", Metallurgy: "ਧਾਤ ਵਿਗਿਆਨ", Mixology: "ਮਿਕਸੋਲੋਜੀ",
      "Mortuary Services": "ਅੰਤਿਮ ਸੰਸਕਾਰ ਸੇਵਾਵਾਂ", Museum: "ਅਜਾਇਬਘਰ", Painting: "ਚਿਤਰਕਲਾ", "Pest Control": "ਕੀਟ ਨਿਯੰਤਰਣ", Plumbing: "ਪਲੰਬਿੰਗ",
      "Postal Service": "ਡਾਕ ਸੇਵਾ", Psychology: "ਮਨੋਵਿਗਿਆਨ", "Real Estate": "ਰੀਅਲ ਐਸਟੇਟ", "Social Work": "ਸਮਾਜਿਕ ਕੰਮ", Software: "ਸਾਫਟਵੇਅਰ",
      Spirituality: "ਆਧਿਆਤਮਿਕਤਾ", Sports: "ਖੇਡਾਂ", Statistics: "ਅੰਕੜਾ ਵਿਗਿਆਨ", Technology: "ਟੈਕਨੋਲੋਜੀ", "Theme Parks": "ਥੀਮ ਪਾਰਕ", Other: "ਹੋਰ", Undecided: "ਅਣਨਿਰਧਾਰਤ",
    },
    sexualPreferenceLabels: {
      Heterosexual: "ਵਿਸ਼ਮਲਿੰਗੀ", Homosexual: "ਸਮਲਿੰਗੀ", Bisexual: "ਦੋਹਰੇ ਲਿੰਗ ਵੱਲ ਆਕਰਸ਼ਣ", Pansexual: "ਸਭ ਲਿੰਗਾਂ ਵੱਲ ਆਕਰਸ਼ਣ",
      Asexual: "ਅਲੈੰਗਿਕ", Questioning: "ਖੋਜ ਵਿੱਚ", "Prefer not to say": "ਦੱਸਣਾ ਪਸੰਦ ਨਹੀਂ", Other: "ਹੋਰ",
    },
    drugLabels: {
      Alcohol: "ਸ਼ਰਾਬ", Cannabis: "ਕੈਨਾਬਿਸ", Nicotine: "ਨਿਕੋਟੀਨ", Coffee: "ਕੌਫੀ", Psychedelics: "ਸਾਇਕੇਡੈਲਿਕਸ", Stimulants: "ਉਤੇਜਕ",
      Opioids: "ਓਪਿਓਇਡਜ਼", Benzodiazepines: "ਬੈਂਜ਼ੋਡਾਇਜ਼ੇਪਾਈਨਜ਼", "MDMA (e.g., ecstasy)": "MDMA (ਜਿਵੇਂ ਐਕਸਟੇਸੀ)", Cocaine: "ਕੋਕੇਨ",
      Heroin: "ਹੈਰੋਇਨ", Methamphetamine: "ਮੇਥਐਮਫੈਟਾਮੀਨ", Ketamine: "ਕੀਟਾਮੀਨ", Fentanyl: "ਫੈਂਟੈਨਿਲ", Other: "ਹੋਰ", "No drug use": "ਨਸ਼ਿਆਂ ਦੀ ਵਰਤੋਂ ਨਹੀਂ",
    },
    helpLabels: {
      Depression: "ਡਿਪ੍ਰੈਸ਼ਨ", Anxiety: "ਚਿੰਤਾ", Addiction: "ਲਤ", "Eating disorder": "ਖੁਰਾਕ ਸੰਬੰਧੀ ਵਿਗਾੜ", "Sleep disorder": "ਨੀੰਦ ਦਾ ਵਿਗਾੜ",
      "Fitness training": "ਫਿਟਨੈੱਸ ਟ੍ਰੇਨਿੰਗ", "Career counseling": "ਕੈਰੀਅਰ ਸਲਾਹ", "Spiritual counseling": "ਆਧਿਆਤਮਿਕ ਸਲਾਹ", "Relationship counseling": "ਰਿਸ਼ਤਾ ਸਲਾਹ", "Something else": "ਕੁਝ ਹੋਰ",
    },
    spiritualAffiliationLabels: {
      Atheist: "ਨਾਸ਼ਤਿਕ", Agnostic: "ਅਗਿਆਤਵਾਦੀ", "Spiritual but not religious": "ਆਧਿਆਤਮਿਕ ਪਰ ਧਾਰਮਿਕ ਨਹੀਂ", Christianity: "ਈਸਾਈ ਧਰਮ",
      Catholicism: "ਕੈਥੋਲਿਕ ਧਰਮ", "Orthodox Christianity": "ਆਰਥੋਡਾਕਸ ਈਸਾਈ ਧਰਮ", "Protestant Christianity": "ਪ੍ਰੋਟੈਸਟੈਂਟ ਈਸਾਈ ਧਰਮ",
      Judaism: "ਯਹੂਦੀ ਧਰਮ", Islam: "ਇਸਲਾਮ", Sufism: "ਸੂਫ਼ੀਵਾਦ", Hinduism: "ਹਿੰਦੂ ਧਰਮ", Sikhism: "ਸਿੱਖ ਧਰਮ", Buddhism: "ਬੁੱਧ ਧਰਮ",
      Taoism: "ਤਾਓਵਾਦ", Confucianism: "ਕਨਫ਼ਿਊਸ਼ੀਅਸਵਾਦ", Jainism: "ਜੈਨ ਧਰਮ", Zoroastrianism: "ਜ਼ਰਥੁਸਤਰੀ ਧਰਮ", "Baháʼí": "ਬਹਾਈ",
      Paganism: "ਪੈਗਨ ਧਾਰਣਾ", Wicca: "ਵਿਕਾ", Shamanism: "ਸ਼ਮਾਨਵਾਦ", Animism: "ਆਤਮਵਾਦ", "Indigenous spirituality": "ਮੂਲ ਨਿਵਾਸੀ ਆਧਿਆਤਮਿਕਤਾ",
      Occultism: "ਗੂੜ੍ਹਵਾਦ", Hermeticism: "ਹਰਮੇਟਿਸਮ", "New Age": "ਨਿਊ ਏਜ", Astrology: "ਜੋਤਿਸ਼", "Esoteric Christianity": "ਗੂੜ੍ਹ ਈਸਾਈ ਧਰਮ",
      Gnosticism: "ਗਨੌਸਟਿਸਿਜ਼ਮ", Mysticism: "ਰਹੱਸਵਾਦ", "Not sure": "ਪੱਕਾ ਨਹੀਂ", "Prefer not to say": "ਦੱਸਣਾ ਪਸੰਦ ਨਹੀਂ",
    },
    socioeconomicLabels: {
      "No income": "ਕੋਈ ਆਮਦਨ ਨਹੀਂ", "$0–$20,000": "$0–$20,000", "$20,000–$40,000": "$20,000–$40,000", "$40,000–$70,000": "$40,000–$70,000",
      "$70,000–$100,000": "$70,000–$100,000", "$100,000–$200,000": "$100,000–$200,000", "$200,000+": "$200,000+",
    },
    livingSituationLabels: {
      "Rent/own": "ਕਿਰਾਏ ਤੇ / ਆਪਣਾ", "Live with parents": "ਮਾਪਿਆਂ ਨਾਲ ਰਹਿੰਦੇ ਹੋ", Homeless: "ਬੇਘਰ", Nomadic: "ਘੁੰਮੰਤੂ", Couchsurfing: "ਦੋਸਤਾਂ ਕੋਲ ਰਹਿਣਾ", Other: "ਹੋਰ",
    },
    fastingLabels: {
      "Yes, intermittent fasting": "ਹਾਂ, ਅੰਤਰਾਲ ਉਪਵਾਸ", "Yes, long fasting": "ਹਾਂ, ਲੰਮਾ ਉਪਵਾਸ", "Yes, dry fasting": "ਹਾਂ, ਸੁੱਕਾ ਉਪਵਾਸ", "No, never fasted": "ਨਹੀਂ, ਕਦੇ ਉਪਵਾਸ ਨਹੀਂ ਕੀਤਾ",
    },
    workoutLabels: {
      "Once a month": "ਮਹੀਨੇ ਵਿੱਚ ਇਕ ਵਾਰ", "Once a week": "ਹਫ਼ਤੇ ਵਿੱਚ ਇਕ ਵਾਰ", "More than once a week": "ਹਫ਼ਤੇ ਵਿੱਚ ਇਕ ਤੋਂ ਵੱਧ ਵਾਰ", Never: "ਕਦੇ ਨਹੀਂ",
    },
  },
  zh: {
    ...en,
    metaTitle: "客户问卷 | Astrology Today",
    metaDescription: "Astrology Today 会员的客户登记问卷。",
    selectOption: "选择一个选项",
    yes: "是",
    no: "否",
    sometimes: "有时",
    backToAstrologyToday: "返回 Astrology Today",
    questionLabel: (n) => `问题 ${n}`,
    finalStep: "最后一步",
    birthTitle: "出生日期",
    monthLabel: "月份 (MM)",
    dayLabel: "日期 (DD)",
    yearLabel: "年份 (YYYY)",
    countryOfOrigin: "原籍国家",
    fieldTitle: "您的工作领域 / 兴趣领域是什么？",
    fieldAria: "工作或兴趣领域",
    sexualPreferenceTitle: "性取向",
    drugUseTitle: "是否使用药物？",
    helpTitle: "您今天希望在哪方面获得帮助？",
    spiritualityTitle: "您的精神/信仰归属是什么？",
    socioeconomicTitle: "您的年收入是多少？",
    livingSituationTitle: "您的居住情况是什么？",
    liveAloneTitle: "您独居吗？",
    fastingTitle: "您曾经禁食过吗？",
    workoutTitle: "您多久锻炼一次？",
    vitaminsTitle: "您服用维生素或氨基酸吗？",
    medicationsTitle: "您是否服用任何药物？请说明。",
    medicationsPlaceholder: "请在此输入您的回答",
    sessionTitle: "选择咨询频率和时长",
    frequency: "频率",
    duration: "时长",
    estimatedMembershipPrice: "预估会员价格",
    back: "返回",
    next: "下一步",
    redirecting: "正在跳转...",
    proceedToCheckout: "前往结账",
    sessionFrequencyLabels: { Monthly: "每月", Biweekly: "每两周", Weekly: "每周" },
    sessionDurationLabels: { "30-minute": "30 分钟", "60-minute": "60 分钟" },
    liveAloneLabels: { Yes: "是", No: "否", Sometimes: "有时" },
    workFieldLabels: {
      Accounting: "会计", Agriculture: "农业", Animals: "动物", Architecture: "建筑", Astrology: "占星", Astronomy: "天文学",
      Automobiles: "汽车", Business: "商业", Casino: "赌场", Chemistry: "化学", "Child Care": "儿童照护", Cleaning: "清洁",
      Design: "设计", Education: "教育", Electricity: "电力", "Emergency Services": "紧急服务", Entertainment: "娱乐", Ethics: "伦理",
      "Event Planning": "活动策划", "Fashion & Beauty": "时尚与美容", Finance: "金融", Fitness: "健身", Food: "食品",
      Forestry: "林业", Fundraising: "筹款", Government: "政府", Jewellery: "珠宝", Landscaping: "景观设计", Law: "法律",
      Library: "图书馆", Logistics: "物流", Locomotives: "火车机车", Medicine: "医学", Metallurgy: "冶金", Mixology: "调酒学",
      "Mortuary Services": "殡葬服务", Museum: "博物馆", Painting: "绘画", "Pest Control": "虫害防治", Plumbing: "管道",
      "Postal Service": "邮政服务", Psychology: "心理学", "Real Estate": "房地产", "Social Work": "社会工作", Software: "软件",
      Spirituality: "灵性", Sports: "体育", Statistics: "统计学", Technology: "科技", "Theme Parks": "主题公园", Other: "其他", Undecided: "未决定",
    },
    sexualPreferenceLabels: {
      Heterosexual: "异性恋", Homosexual: "同性恋", Bisexual: "双性恋", Pansexual: "泛性恋", Asexual: "无性恋", Questioning: "探索中", "Prefer not to say": "不愿透露", Other: "其他",
    },
    drugLabels: {
      Alcohol: "酒精", Cannabis: "大麻", Nicotine: "尼古丁", Coffee: "咖啡", Psychedelics: "迷幻药", Stimulants: "兴奋剂", Opioids: "阿片类",
      Benzodiazepines: "苯二氮卓类", "MDMA (e.g., ecstasy)": "MDMA（如摇头丸）", Cocaine: "可卡因", Heroin: "海洛因", Methamphetamine: "甲基苯丙胺", Ketamine: "氯胺酮", Fentanyl: "芬太尼", Other: "其他", "No drug use": "不使用药物",
    },
    helpLabels: {
      Depression: "抑郁", Anxiety: "焦虑", Addiction: "成瘾", "Eating disorder": "进食障碍", "Sleep disorder": "睡眠障碍", "Fitness training": "健身训练", "Career counseling": "职业咨询", "Spiritual counseling": "灵性咨询", "Relationship counseling": "关系咨询", "Something else": "其他",
    },
    spiritualAffiliationLabels: {
      Atheist: "无神论", Agnostic: "不可知论", "Spiritual but not religious": "有灵性但无宗教", Christianity: "基督教", Catholicism: "天主教",
      "Orthodox Christianity": "东正教", "Protestant Christianity": "新教", Judaism: "犹太教", Islam: "伊斯兰教", Sufism: "苏菲主义", Hinduism: "印度教",
      Sikhism: "锡克教", Buddhism: "佛教", Taoism: "道教", Confucianism: "儒家", Jainism: "耆那教", Zoroastrianism: "琐罗亚斯德教", "Baháʼí": "巴哈伊",
      Paganism: "异教", Wicca: "威卡教", Shamanism: "萨满教", Animism: "泛灵论", "Indigenous spirituality": "原住民灵性", Occultism: "神秘学", Hermeticism: "赫尔墨斯主义", "New Age": "新时代", Astrology: "占星", "Esoteric Christianity": "神秘基督教", Gnosticism: "诺斯替主义", Mysticism: "神秘主义", "Not sure": "不确定", "Prefer not to say": "不愿透露",
    },
    socioeconomicLabels: {
      "No income": "无收入", "$0–$20,000": "$0–$20,000", "$20,000–$40,000": "$20,000–$40,000", "$40,000–$70,000": "$40,000–$70,000", "$70,000–$100,000": "$70,000–$100,000", "$100,000–$200,000": "$100,000–$200,000", "$200,000+": "$200,000+",
    },
    livingSituationLabels: {
      "Rent/own": "租房 / 自有住房", "Live with parents": "与父母同住", Homeless: "无家可归", Nomadic: "游居", Couchsurfing: "借宿", Other: "其他",
    },
    fastingLabels: {
      "Yes, intermittent fasting": "是，间歇性禁食", "Yes, long fasting": "是，长期禁食", "Yes, dry fasting": "是，干性禁食", "No, never fasted": "没有，从未禁食过",
    },
    workoutLabels: {
      "Once a month": "每月一次", "Once a week": "每周一次", "More than once a week": "每周超过一次", Never: "从不",
    },
  },
  ja: {
    ...en,
    metaTitle: "クライアント質問票 | Astrology Today",
    metaDescription: "Astrology Today メンバーシップのためのクライアント登録質問票です。",
    selectOption: "オプションを選択",
    yes: "はい",
    no: "いいえ",
    sometimes: "ときどき",
    backToAstrologyToday: "Astrology Today に戻る",
    questionLabel: (n) => `質問 ${n}`,
    finalStep: "最終ステップ",
    birthTitle: "生年月日",
    monthLabel: "月 (MM)",
    dayLabel: "日 (DD)",
    yearLabel: "年 (YYYY)",
    countryOfOrigin: "出身国",
    fieldTitle: "あなたの仕事分野 / 関心分野は何ですか？",
    fieldAria: "仕事または関心分野",
    sexualPreferenceTitle: "性的指向",
    drugUseTitle: "薬物使用はありますか？",
    helpTitle: "今日は何についてサポートを求めていますか？",
    spiritualityTitle: "あなたのスピリチュアルな所属は何ですか？",
    socioeconomicTitle: "あなたの年収はいくらですか？",
    livingSituationTitle: "あなたの居住状況はどうですか？",
    liveAloneTitle: "一人暮らしですか？",
    fastingTitle: "断食をしたことがありますか？",
    workoutTitle: "どのくらいの頻度で運動しますか？",
    vitaminsTitle: "ビタミンやアミノ酸を摂取していますか？",
    medicationsTitle: "服用している薬はありますか？詳しくご記入ください。",
    medicationsPlaceholder: "ここに回答を入力してください",
    sessionTitle: "セッションの頻度と時間を選択",
    frequency: "頻度",
    duration: "時間",
    estimatedMembershipPrice: "推定メンバーシップ料金",
    back: "戻る",
    next: "次へ",
    redirecting: "リダイレクト中...",
    proceedToCheckout: "チェックアウトへ進む",
    sessionFrequencyLabels: { Monthly: "毎月", Biweekly: "隔週", Weekly: "毎週" },
    sessionDurationLabels: { "30-minute": "30分", "60-minute": "60分" },
    liveAloneLabels: { Yes: "はい", No: "いいえ", Sometimes: "ときどき" },
    workFieldLabels: {
      Accounting: "会計", Agriculture: "農業", Animals: "動物", Architecture: "建築", Astrology: "占星術", Astronomy: "天文学", Automobiles: "自動車",
      Business: "ビジネス", Casino: "カジノ", Chemistry: "化学", "Child Care": "育児", Cleaning: "清掃", Design: "デザイン", Education: "教育",
      Electricity: "電気", "Emergency Services": "緊急サービス", Entertainment: "エンターテインメント", Ethics: "倫理", "Event Planning": "イベント企画",
      "Fashion & Beauty": "ファッションと美容", Finance: "金融", Fitness: "フィットネス", Food: "食品", Forestry: "林業", Fundraising: "資金調達",
      Government: "政府", Jewellery: "ジュエリー", Landscaping: "造園", Law: "法律", Library: "図書館", Logistics: "物流", Locomotives: "機関車",
      Medicine: "医療", Metallurgy: "冶金", Mixology: "ミクソロジー", "Mortuary Services": "葬祭サービス", Museum: "博物館", Painting: "絵画",
      "Pest Control": "害虫駆除", Plumbing: "配管", "Postal Service": "郵便サービス", Psychology: "心理学", "Real Estate": "不動産", "Social Work": "ソーシャルワーク",
      Software: "ソフトウェア", Spirituality: "スピリチュアリティ", Sports: "スポーツ", Statistics: "統計学", Technology: "テクノロジー", "Theme Parks": "テーマパーク", Other: "その他", Undecided: "未定",
    },
    sexualPreferenceLabels: {
      Heterosexual: "異性愛", Homosexual: "同性愛", Bisexual: "両性愛", Pansexual: "パンセクシュアル", Asexual: "無性愛", Questioning: "模索中", "Prefer not to say": "答えたくない", Other: "その他",
    },
    drugLabels: {
      Alcohol: "アルコール", Cannabis: "カンナビス", Nicotine: "ニコチン", Coffee: "コーヒー", Psychedelics: "サイケデリック", Stimulants: "刺激薬", Opioids: "オピオイド",
      Benzodiazepines: "ベンゾジアゼピン", "MDMA (e.g., ecstasy)": "MDMA（例：エクスタシー）", Cocaine: "コカイン", Heroin: "ヘロイン", Methamphetamine: "メタンフェタミン", Ketamine: "ケタミン", Fentanyl: "フェンタニル", Other: "その他", "No drug use": "薬物使用なし",
    },
    helpLabels: {
      Depression: "うつ", Anxiety: "不安", Addiction: "依存", "Eating disorder": "摂食障害", "Sleep disorder": "睡眠障害", "Fitness training": "フィットネストレーニング", "Career counseling": "キャリアカウンセリング", "Spiritual counseling": "スピリチュアルカウンセリング", "Relationship counseling": "関係カウンセリング", "Something else": "その他",
    },
    spiritualAffiliationLabels: {
      Atheist: "無神論", Agnostic: "不可知論", "Spiritual but not religious": "宗教的ではないがスピリチュアル", Christianity: "キリスト教", Catholicism: "カトリック",
      "Orthodox Christianity": "正教会", "Protestant Christianity": "プロテスタント", Judaism: "ユダヤ教", Islam: "イスラム教", Sufism: "スーフィズム", Hinduism: "ヒンドゥー教", Sikhism: "シク教", Buddhism: "仏教", Taoism: "道教", Confucianism: "儒教", Jainism: "ジャイナ教", Zoroastrianism: "ゾロアスター教", "Baháʼí": "バハイ教", Paganism: "異教", Wicca: "ウィッカ", Shamanism: "シャーマニズム", Animism: "アニミズム", "Indigenous spirituality": "先住民の精神性", Occultism: "オカルティズム", Hermeticism: "ヘルメティズム", "New Age": "ニューエイジ", Astrology: "占星術", "Esoteric Christianity": "秘教的キリスト教", Gnosticism: "グノーシス主義", Mysticism: "神秘主義", "Not sure": "よくわからない", "Prefer not to say": "答えたくない",
    },
    socioeconomicLabels: {
      "No income": "収入なし", "$0–$20,000": "$0–$20,000", "$20,000–$40,000": "$20,000–$40,000", "$40,000–$70,000": "$40,000–$70,000", "$70,000–$100,000": "$70,000–$100,000", "$100,000–$200,000": "$100,000–$200,000", "$200,000+": "$200,000+",
    },
    livingSituationLabels: {
      "Rent/own": "賃貸 / 持ち家", "Live with parents": "親と同居", Homeless: "ホームレス", Nomadic: "遊牧的", Couchsurfing: "カウチサーフィン", Other: "その他",
    },
    fastingLabels: {
      "Yes, intermittent fasting": "はい、断続的断食", "Yes, long fasting": "はい、長期断食", "Yes, dry fasting": "はい、ドライ断食", "No, never fasted": "いいえ、断食したことはない",
    },
    workoutLabels: {
      "Once a month": "月に一度", "Once a week": "週に一度", "More than once a week": "週に一度以上", Never: "まったくしない",
    },
  },
  yue: {
    ...en,
    metaTitle: "客戶問卷 | Astrology Today",
    metaDescription: "Astrology Today 會員嘅客戶登記問卷。",
    selectOption: "選擇一個選項",
    yes: "係",
    no: "唔係",
    sometimes: "有時",
    backToAstrologyToday: "返回 Astrology Today",
    questionLabel: (n) => `問題 ${n}`,
    finalStep: "最後一步",
    birthTitle: "出生日期",
    monthLabel: "月份 (MM)",
    dayLabel: "日期 (DD)",
    yearLabel: "年份 (YYYY)",
    countryOfOrigin: "原居國家",
    fieldTitle: "你嘅工作領域 / 興趣領域係咩？",
    fieldAria: "工作或興趣領域",
    sexualPreferenceTitle: "性取向",
    drugUseTitle: "有冇使用藥物？",
    helpTitle: "你今日想喺邊方面得到幫助？",
    spiritualityTitle: "你嘅靈性歸屬係咩？",
    socioeconomicTitle: "你嘅年收入係幾多？",
    livingSituationTitle: "你嘅居住情況係點？",
    liveAloneTitle: "你係咪自己一個住？",
    fastingTitle: "你有冇試過禁食？",
    workoutTitle: "你幾耐做一次運動？",
    vitaminsTitle: "你有冇食維他命或胺基酸？",
    medicationsTitle: "你有冇服用任何藥物？請說明。",
    medicationsPlaceholder: "喺呢度輸入你嘅回答",
    sessionTitle: "選擇會談頻率同時長",
    frequency: "頻率",
    duration: "時長",
    estimatedMembershipPrice: "預估會員價格",
    back: "返回",
    next: "下一步",
    redirecting: "跳轉中...",
    proceedToCheckout: "前往結帳",
    sessionFrequencyLabels: { Monthly: "每月", Biweekly: "每兩週", Weekly: "每週" },
    sessionDurationLabels: { "30-minute": "30 分鐘", "60-minute": "60 分鐘" },
    liveAloneLabels: { Yes: "係", No: "唔係", Sometimes: "有時" },
    workFieldLabels: {
      Accounting: "會計", Agriculture: "農業", Animals: "動物", Architecture: "建築", Astrology: "占星", Astronomy: "天文學", Automobiles: "汽車",
      Business: "商業", Casino: "賭場", Chemistry: "化學", "Child Care": "兒童照顧", Cleaning: "清潔", Design: "設計", Education: "教育",
      Electricity: "電力", "Emergency Services": "緊急服務", Entertainment: "娛樂", Ethics: "倫理", "Event Planning": "活動策劃",
      "Fashion & Beauty": "時尚同美容", Finance: "金融", Fitness: "健身", Food: "飲食", Forestry: "林業", Fundraising: "籌款",
      Government: "政府", Jewellery: "珠寶", Landscaping: "園景設計", Law: "法律", Library: "圖書館", Logistics: "物流", Locomotives: "火車頭",
      Medicine: "醫學", Metallurgy: "冶金", Mixology: "調酒學", "Mortuary Services": "殯葬服務", Museum: "博物館", Painting: "繪畫",
      "Pest Control": "滅蟲", Plumbing: "水喉", "Postal Service": "郵政服務", Psychology: "心理學", "Real Estate": "房地產", "Social Work": "社會工作",
      Software: "軟件", Spirituality: "靈性", Sports: "體育", Statistics: "統計學", Technology: "科技", "Theme Parks": "主題公園", Other: "其他", Undecided: "未決定",
    },
    sexualPreferenceLabels: {
      Heterosexual: "異性戀", Homosexual: "同性戀", Bisexual: "雙性戀", Pansexual: "泛性戀", Asexual: "無性戀", Questioning: "探索中", "Prefer not to say": "唔想講", Other: "其他",
    },
    drugLabels: {
      Alcohol: "酒精", Cannabis: "大麻", Nicotine: "尼古丁", Coffee: "咖啡", Psychedelics: "迷幻藥", Stimulants: "興奮劑", Opioids: "鴉片類",
      Benzodiazepines: "苯二氮平類", "MDMA (e.g., ecstasy)": "MDMA（例如搖頭丸）", Cocaine: "可卡因", Heroin: "海洛英", Methamphetamine: "冰毒", Ketamine: "K仔", Fentanyl: "芬太尼", Other: "其他", "No drug use": "冇藥物使用",
    },
    helpLabels: {
      Depression: "抑鬱", Anxiety: "焦慮", Addiction: "成癮", "Eating disorder": "飲食失調", "Sleep disorder": "睡眠障礙", "Fitness training": "健身訓練", "Career counseling": "職業輔導", "Spiritual counseling": "靈性輔導", "Relationship counseling": "感情輔導", "Something else": "其他",
    },
    spiritualAffiliationLabels: {
      Atheist: "無神論", Agnostic: "不可知論", "Spiritual but not religious": "有靈性但冇宗教", Christianity: "基督教", Catholicism: "天主教",
      "Orthodox Christianity": "東正教", "Protestant Christianity": "新教", Judaism: "猶太教", Islam: "伊斯蘭教", Sufism: "蘇菲主義", Hinduism: "印度教",
      Sikhism: "錫克教", Buddhism: "佛教", Taoism: "道教", Confucianism: "儒家", Jainism: "耆那教", Zoroastrianism: "祆教", "Baháʼí": "巴哈伊",
      Paganism: "異教", Wicca: "威卡教", Shamanism: "薩滿教", Animism: "泛靈論", "Indigenous spirituality": "原住民靈性", Occultism: "神秘學", Hermeticism: "赫耳墨斯主義", "New Age": "新時代", Astrology: "占星", "Esoteric Christianity": "神秘基督教", Gnosticism: "諾斯底主義", Mysticism: "神秘主義", "Not sure": "唔肯定", "Prefer not to say": "唔想講",
    },
    socioeconomicLabels: {
      "No income": "冇收入", "$0–$20,000": "$0–$20,000", "$20,000–$40,000": "$20,000–$40,000", "$40,000–$70,000": "$40,000–$70,000", "$70,000–$100,000": "$70,000–$100,000", "$100,000–$200,000": "$100,000–$200,000", "$200,000+": "$200,000+",
    },
    livingSituationLabels: {
      "Rent/own": "租住 / 自置", "Live with parents": "同父母住", Homeless: "無家可歸", Nomadic: "遊牧式", Couchsurfing: "借住朋友屋企", Other: "其他",
    },
    fastingLabels: {
      "Yes, intermittent fasting": "有，間歇性斷食", "Yes, long fasting": "有，長時間斷食", "Yes, dry fasting": "有，乾斷食", "No, never fasted": "冇，從未試過斷食",
    },
    workoutLabels: {
      "Once a month": "每月一次", "Once a week": "每週一次", "More than once a week": "每週多於一次", Never: "從不",
    },
  },
  ko: {
    ...en,
    metaTitle: "클라이언트 설문지 | Astrology Today",
    metaDescription: "Astrology Today 멤버십을 위한 클라이언트 등록 설문지입니다.",
    selectOption: "옵션을 선택하세요",
    yes: "예",
    no: "아니오",
    sometimes: "가끔",
    backToAstrologyToday: "Astrology Today로 돌아가기",
    questionLabel: (n) => `질문 ${n}`,
    finalStep: "마지막 단계",
    birthTitle: "생년월일",
    monthLabel: "월 (MM)",
    dayLabel: "일 (DD)",
    yearLabel: "연도 (YYYY)",
    countryOfOrigin: "출신 국가",
    fieldTitle: "당신의 직업 분야 / 관심 분야는 무엇인가요?",
    fieldAria: "직업 또는 관심 분야",
    sexualPreferenceTitle: "성적 지향",
    drugUseTitle: "약물 사용 여부?",
    helpTitle: "오늘 어떤 부분에서 도움을 원하시나요?",
    spiritualityTitle: "당신의 영적 소속은 무엇인가요?",
    socioeconomicTitle: "연간 수입은 얼마인가요?",
    livingSituationTitle: "현재 거주 상황은 어떤가요?",
    liveAloneTitle: "혼자 사시나요?",
    fastingTitle: "금식을 해본 적이 있나요?",
    workoutTitle: "얼마나 자주 운동하나요?",
    vitaminsTitle: "비타민이나 아미노산을 복용하나요?",
    medicationsTitle: "복용 중인 약이 있나요? 자세히 적어 주세요.",
    medicationsPlaceholder: "여기에 답변을 입력하세요",
    sessionTitle: "세션 빈도와 시간을 선택하세요",
    frequency: "빈도",
    duration: "시간",
    estimatedMembershipPrice: "예상 멤버십 가격",
    back: "뒤로",
    next: "다음",
    redirecting: "이동 중...",
    proceedToCheckout: "결제로 진행",
    sessionFrequencyLabels: { Monthly: "매월", Biweekly: "격주", Weekly: "매주" },
    sessionDurationLabels: { "30-minute": "30분", "60-minute": "60분" },
    liveAloneLabels: { Yes: "예", No: "아니오", Sometimes: "가끔" },
    workFieldLabels: {
      Accounting: "회계", Agriculture: "농업", Animals: "동물", Architecture: "건축", Astrology: "점성술", Astronomy: "천문학", Automobiles: "자동차",
      Business: "비즈니스", Casino: "카지노", Chemistry: "화학", "Child Care": "아동 돌봄", Cleaning: "청소", Design: "디자인", Education: "교육",
      Electricity: "전기", "Emergency Services": "응급 서비스", Entertainment: "엔터테인먼트", Ethics: "윤리", "Event Planning": "이벤트 기획",
      "Fashion & Beauty": "패션 및 뷰티", Finance: "금융", Fitness: "피트니스", Food: "식품", Forestry: "임업", Fundraising: "기금 모금",
      Government: "정부", Jewellery: "주얼리", Landscaping: "조경", Law: "법률", Library: "도서관", Logistics: "물류", Locomotives: "기관차",
      Medicine: "의학", Metallurgy: "야금", Mixology: "믹솔로지", "Mortuary Services": "장례 서비스", Museum: "박물관", Painting: "회화",
      "Pest Control": "해충 방제", Plumbing: "배관", "Postal Service": "우편 서비스", Psychology: "심리학", "Real Estate": "부동산", "Social Work": "사회복지",
      Software: "소프트웨어", Spirituality: "영성", Sports: "스포츠", Statistics: "통계학", Technology: "기술", "Theme Parks": "테마파크", Other: "기타", Undecided: "미정",
    },
    sexualPreferenceLabels: {
      Heterosexual: "이성애", Homosexual: "동성애", Bisexual: "양성애", Pansexual: "범성애", Asexual: "무성애", Questioning: "탐색 중", "Prefer not to say": "답변하고 싶지 않음", Other: "기타",
    },
    drugLabels: {
      Alcohol: "알코올", Cannabis: "대마", Nicotine: "니코틴", Coffee: "커피", Psychedelics: "환각제", Stimulants: "흥분제", Opioids: "오피오이드", Benzodiazepines: "벤조디아제핀", "MDMA (e.g., ecstasy)": "MDMA(예: 엑스터시)", Cocaine: "코카인", Heroin: "헤로인", Methamphetamine: "메스암페타민", Ketamine: "케타민", Fentanyl: "펜타닐", Other: "기타", "No drug use": "약물 사용 안 함",
    },
    helpLabels: {
      Depression: "우울증", Anxiety: "불안", Addiction: "중독", "Eating disorder": "섭식 장애", "Sleep disorder": "수면 장애", "Fitness training": "피트니스 훈련", "Career counseling": "진로 상담", "Spiritual counseling": "영적 상담", "Relationship counseling": "관계 상담", "Something else": "기타",
    },
    spiritualAffiliationLabels: {
      Atheist: "무신론", Agnostic: "불가지론", "Spiritual but not religious": "영적이지만 종교적이지 않음", Christianity: "기독교", Catholicism: "가톨릭",
      "Orthodox Christianity": "정교회", "Protestant Christianity": "개신교", Judaism: "유대교", Islam: "이슬람교", Sufism: "수피즘", Hinduism: "힌두교",
      Sikhism: "시크교", Buddhism: "불교", Taoism: "도교", Confucianism: "유교", Jainism: "자이나교", Zoroastrianism: "조로아스터교", "Baháʼí": "바하이", Paganism: "이교", Wicca: "위카", Shamanism: "샤머니즘", Animism: "애니미즘", "Indigenous spirituality": "토착 영성", Occultism: "오컬트", Hermeticism: "헤르메스주의", "New Age": "뉴에이지", Astrology: "점성술", "Esoteric Christianity": "신비 기독교", Gnosticism: "영지주의", Mysticism: "신비주의", "Not sure": "잘 모르겠음", "Prefer not to say": "답변하고 싶지 않음",
    },
    socioeconomicLabels: {
      "No income": "수입 없음", "$0–$20,000": "$0–$20,000", "$20,000–$40,000": "$20,000–$40,000", "$40,000–$70,000": "$40,000–$70,000", "$70,000–$100,000": "$70,000–$100,000", "$100,000–$200,000": "$100,000–$200,000", "$200,000+": "$200,000+",
    },
    livingSituationLabels: {
      "Rent/own": "임대 / 자가", "Live with parents": "부모와 함께 거주", Homeless: "노숙", Nomadic: "유목적 생활", Couchsurfing: "소파 서핑", Other: "기타",
    },
    fastingLabels: {
      "Yes, intermittent fasting": "예, 간헐적 단식", "Yes, long fasting": "예, 장기 단식", "Yes, dry fasting": "예, 건식 단식", "No, never fasted": "아니요, 단식한 적 없음",
    },
    workoutLabels: {
      "Once a month": "한 달에 한 번", "Once a week": "일주일에 한 번", "More than once a week": "일주일에 한 번 이상", Never: "전혀 안 함",
    },
  },
};

export function getClientQuestionnaireCopy(locale: SupportedLocale): ClientQuestionnaireCopy {
  return copyByLocale[locale] ?? copyByLocale[defaultLocale];
}
